//! Leyline Studio desktop application (`docs/roadmap.md` phase 5).
//!
//! The library browser. Studio opens a library through the SDK — never the
//! catalog directly — renders the photo grid with cached thumbnails, lets
//! the user filter, sort and classify (rate, label, flag) photos, shows
//! the metadata of the selected photo, and develops it non-destructively
//! in a dedicated view (`D` enters, `G` leaves).

mod classify;
mod develop;
mod format;

/// UI generated by `slint-build` from `ui/studio.slint`.
#[allow(missing_docs, clippy::all)]
mod ui {
    slint::include_modules!();
}

use std::cell::RefCell;
use std::collections::VecDeque;
use std::path::Path;
use std::rc::Rc;
use std::time::Duration;

use classify::Action;
use leyline_sdk::{
    AssetId, CollectionId, CollectionNode, CollectionType, ColorLabel, ExportPreset, ExportReport,
    ExportSettings, GridItem, GridQuery, ImportOptions, Library, PickState, PreviewKind, Settings,
    SkippedFile, Sort, VersionId,
};
use slint::{ComponentHandle, Model, ModelRc, SharedString, Timer, TimerMode, VecModel};

use ui::{Cell, StudioWindow};

/// Sort orders the header button cycles through, with their labels.
const SORTS: [(Sort, &str); 8] = [
    (Sort::CaptureDate { ascending: false }, "capture ↓"),
    (Sort::CaptureDate { ascending: true }, "capture ↑"),
    (Sort::Filename { ascending: true }, "filename A–Z"),
    (Sort::Filename { ascending: false }, "filename Z–A"),
    (Sort::ImportedAt { ascending: false }, "imported ↓"),
    (Sort::ImportedAt { ascending: true }, "imported ↑"),
    (Sort::Rating { ascending: false }, "rating ↓"),
    (Sort::Rating { ascending: true }, "rating ↑"),
];

/// Application state shared by every UI callback.
struct App {
    library: Library,
    query: GridQuery,
    /// Rows currently displayed, parallel to the grid cell model.
    items: Vec<GridItem>,
    /// The photo open in the develop view, when in develop mode.
    develop: Option<(AssetId, VersionId)>,
    /// Stored export presets, parallel to the dialog's preset chips.
    presets: Vec<ExportPreset>,
    /// Flattened collection ids, parallel to the sidebar rows.
    collections: Vec<CollectionId>,
    /// The live cell model, so thumbnails can be filled in row by row.
    cells: Rc<VecModel<Cell>>,
    /// Grid rows still waiting for a thumbnail, drained by the timer.
    pending: VecDeque<usize>,
}

fn main() -> std::process::ExitCode {
    match run() {
        Ok(()) => std::process::ExitCode::SUCCESS,
        Err(message) => {
            eprintln!("error: {message}");
            std::process::ExitCode::FAILURE
        }
    }
}

fn run() -> Result<(), String> {
    let Some(root) = std::env::args().nth(1) else {
        return Err("usage: leyline-studio <library-dir>".to_owned());
    };
    let library = Library::open(Path::new(&root)).map_err(|e| e.to_string())?;
    let info = library.catalog().library().map_err(|e| e.to_string())?;

    let app = Rc::new(RefCell::new(App {
        library,
        query: GridQuery::default(),
        items: Vec::new(),
        develop: None,
        presets: Vec::new(),
        collections: Vec::new(),
        cells: Rc::new(VecModel::default()),
        pending: VecDeque::new(),
    }));

    let window = StudioWindow::new().map_err(|e| e.to_string())?;
    window.set_library_name(SharedString::from(info.name.as_str()));
    window.set_filter_label(-1);
    window.set_filter_pick(-1);
    window.set_sort_label(SharedString::from(sort_label(GridQuery::default().sort)));
    let palette: Vec<slint::Color> = (0..5)
        .filter_map(ColorLabel::from_i64)
        .map(|label| label_color(Some(label)))
        .collect();
    window.set_label_colors(ModelRc::from(Rc::new(VecModel::from(palette))));

    {
        let mut app = app.borrow_mut();
        refresh_collections(&mut app, &window)?;
        reload(&mut app, &window)?;
    }

    wire_select(&app, &window);
    wire_classify(&app, &window);
    wire_filters(&app, &window);
    wire_develop(&app, &window);
    wire_dialogs(&app, &window);
    wire_collections(&app, &window);
    // Kept alive until the event loop ends: dropping the timer stops it.
    let _thumbnails = thumbnail_timer(&app);

    window.run().map_err(|e| e.to_string())
}

/// Starts the timer that renders one missing thumbnail per tick, filling
/// the grid progressively without blocking startup on a full render.
fn thumbnail_timer(app: &Rc<RefCell<App>>) -> Timer {
    let app = Rc::clone(app);
    let timer = Timer::default();
    timer.start(TimerMode::Repeated, Duration::from_millis(30), move || {
        let mut app = app.borrow_mut();
        let Some(index) = app.pending.pop_front() else {
            return;
        };
        let Some(asset) = app.items.get(index).map(|item| item.asset_id) else {
            return;
        };
        let thumbnail = match app.library.preview(asset, PreviewKind::Thumbnail) {
            Ok(file) => slint::Image::load_from_path(&file.path).unwrap_or_default(),
            Err(error) => {
                eprintln!("error: {error}");
                return;
            }
        };
        if let Some(mut cell) = app.cells.row_data(index) {
            cell.thumbnail = thumbnail;
            app.cells.set_row_data(index, cell);
        }
    });
    timer
}

/// Fills the side panel when a cell is clicked or reached with the arrows.
fn wire_select(app: &Rc<RefCell<App>>, window: &StudioWindow) {
    let app = Rc::clone(app);
    let handle = window.as_weak();
    window.on_select(move |index| {
        let Some(window) = handle.upgrade() else {
            return;
        };
        show_details(&app.borrow(), &window, index);
    });
}

/// Applies a classement key (`0`–`9`, `p`, `x`, `u`) to the selection.
fn wire_classify(app: &Rc<RefCell<App>>, window: &StudioWindow) {
    let app = Rc::clone(app);
    let handle = window.as_weak();
    window.on_classify(move |key| {
        let Some(window) = handle.upgrade() else {
            return;
        };
        let mut app = app.borrow_mut();
        let Some((version, label, pick)) = usize::try_from(window.get_selected())
            .ok()
            .and_then(|i| app.items.get(i))
            .map(|item| (item.version_id, item.color_label, item.pick))
        else {
            return;
        };
        let Some(action) = classify::from_key(key.as_str(), label, pick) else {
            return;
        };
        let catalog = app.library.catalog_mut();
        let applied = match action {
            Action::Rate(rating) => catalog.set_rating(&[version], rating),
            Action::Label(label) => catalog.set_color_label(&[version], label),
            Action::Flag(pick) => catalog.set_pick(&[version], pick),
        };
        if let Err(error) = applied
            .map_err(|e| e.to_string())
            .and_then(|()| reload(&mut app, &window))
        {
            report_error(&window, &error);
        }
    });
}

/// Connects the filter bar: stars, label dots, pick chips, sort cycling.
fn wire_filters(app: &Rc<RefCell<App>>, window: &StudioWindow) {
    let on_error = |window: &StudioWindow, result: Result<(), String>| {
        if let Err(error) = result {
            report_error(window, &error);
        }
    };

    {
        let app = Rc::clone(app);
        let handle = window.as_weak();
        window.on_rating_filter(move |stars| {
            let Some(window) = handle.upgrade() else {
                return;
            };
            let mut app = app.borrow_mut();
            app.query.rating_at_least =
                classify::toggle_rating_filter(app.query.rating_at_least, stars as u8);
            window.set_filter_rating(app.query.rating_at_least.map_or(0, i32::from));
            on_error(&window, reload(&mut app, &window));
        });
    }
    {
        let app = Rc::clone(app);
        let handle = window.as_weak();
        window.on_label_filter(move |value| {
            let Some(window) = handle.upgrade() else {
                return;
            };
            let Some(clicked) = ColorLabel::from_i64(i64::from(value)) else {
                return;
            };
            let mut app = app.borrow_mut();
            app.query.color_label = classify::toggle_label_filter(app.query.color_label, clicked);
            window.set_filter_label(app.query.color_label.map_or(-1, |l| l.as_i64() as i32));
            on_error(&window, reload(&mut app, &window));
        });
    }
    {
        let app = Rc::clone(app);
        let handle = window.as_weak();
        window.on_pick_filter(move |value| {
            let Some(window) = handle.upgrade() else {
                return;
            };
            let Some(clicked) = PickState::from_i64(i64::from(value)) else {
                return;
            };
            let mut app = app.borrow_mut();
            app.query.pick = classify::toggle_pick_filter(app.query.pick, clicked);
            window.set_filter_pick(app.query.pick.map_or(-1, |p| p.as_i64() as i32));
            on_error(&window, reload(&mut app, &window));
        });
    }
    {
        let app = Rc::clone(app);
        let handle = window.as_weak();
        window.on_search(move |text| {
            let Some(window) = handle.upgrade() else {
                return;
            };
            let mut app = app.borrow_mut();
            let text = text.trim();
            app.query.text = (!text.is_empty()).then(|| text.to_owned());
            on_error(&window, reload(&mut app, &window));
        });
    }
    {
        let app = Rc::clone(app);
        let handle = window.as_weak();
        window.on_cycle_sort(move || {
            let Some(window) = handle.upgrade() else {
                return;
            };
            let mut app = app.borrow_mut();
            let next = SORTS
                .iter()
                .position(|(sort, _)| *sort == app.query.sort)
                .map_or(0, |i| (i + 1) % SORTS.len());
            app.query.sort = SORTS[next].0;
            window.set_sort_label(SharedString::from(SORTS[next].1));
            on_error(&window, reload(&mut app, &window));
        });
    }
}

/// Connects the develop view: entering, sliders, undo / redo, leaving.
fn wire_develop(app: &Rc<RefCell<App>>, window: &StudioWindow) {
    {
        let app = Rc::clone(app);
        let handle = window.as_weak();
        window.on_enter_develop(move || {
            let Some(window) = handle.upgrade() else {
                return;
            };
            let mut app = app.borrow_mut();
            let Some((asset, version, filename)) = usize::try_from(window.get_selected())
                .ok()
                .and_then(|i| app.items.get(i))
                .map(|item| (item.asset_id, item.version_id, item.filename.clone()))
            else {
                return;
            };
            app.develop = Some((asset, version));
            match refresh_develop(&mut app, &window) {
                Ok(()) => {
                    window.set_develop_filename(SharedString::from(filename.as_str()));
                    window.set_develop_mode(true);
                }
                Err(error) => {
                    app.develop = None;
                    report_error(&window, &error);
                }
            }
        });
    }
    {
        let app = Rc::clone(app);
        let handle = window.as_weak();
        window.on_exit_develop(move || {
            let Some(window) = handle.upgrade() else {
                return;
            };
            let mut app = app.borrow_mut();
            app.develop = None;
            window.set_develop_mode(false);
            // Edits invalidated the thumbnails: rebuild the grid.
            if let Err(error) = reload(&mut app, &window) {
                report_error(&window, &error);
            }
        });
    }
    {
        let app = Rc::clone(app);
        let handle = window.as_weak();
        window.on_develop_edit(move |slider, value| {
            let Some(window) = handle.upgrade() else {
                return;
            };
            let mut app = app.borrow_mut();
            let Some((_, version)) = app.develop else {
                return;
            };
            let committed = (|| {
                let mut session = app.library.edit(version)?;
                let Some((param, value)) =
                    develop::action(slider.as_str(), f64::from(value), session.settings())
                else {
                    return Ok(());
                };
                session.set(param, value)?;
                session.commit().map(|_| ())
            })();
            if let Err(error) = committed
                .map_err(|e| e.to_string())
                .and_then(|()| refresh_develop(&mut app, &window))
            {
                report_error(&window, &error);
            }
        });
    }
    {
        let app = Rc::clone(app);
        let handle = window.as_weak();
        window.on_develop_undo(move || {
            if let Some(window) = handle.upgrade() {
                history_step(&mut app.borrow_mut(), &window, true);
            }
        });
    }
    {
        let app = Rc::clone(app);
        let handle = window.as_weak();
        window.on_develop_redo(move || {
            if let Some(window) = handle.upgrade() {
                history_step(&mut app.borrow_mut(), &window, false);
            }
        });
    }
}

/// Connects the import and export dialogs.
fn wire_dialogs(app: &Rc<RefCell<App>>, window: &StudioWindow) {
    {
        let app = Rc::clone(app);
        let handle = window.as_weak();
        window.on_run_import(move |source, copy, recursive| {
            let Some(window) = handle.upgrade() else {
                return;
            };
            let mut app = app.borrow_mut();
            if source.is_empty() {
                window.set_dialog_result(SharedString::from("Enter a source folder."));
                return;
            }
            let options = ImportOptions {
                copy_files: copy,
                recursive,
            };
            match app
                .library
                .import(Path::new(source.as_str()), &options, |_, _| {})
            {
                Ok(report) => {
                    window.set_dialog_result(SharedString::from(import_summary(
                        report.imported.len(),
                        &report.skipped,
                    )));
                    if let Err(error) = reload(&mut app, &window) {
                        eprintln!("error: {error}");
                    }
                }
                Err(error) => {
                    window.set_dialog_result(SharedString::from(format!("Import failed: {error}")));
                }
            }
        });
    }
    {
        let app = Rc::clone(app);
        let handle = window.as_weak();
        window.on_open_export(move || {
            let Some(window) = handle.upgrade() else {
                return;
            };
            let mut app = app.borrow_mut();
            let presets = match app.library.export_presets() {
                Ok(presets) => presets,
                Err(error) => {
                    report_error(&window, &error.to_string());
                    return;
                }
            };
            let names: Vec<SharedString> = presets
                .iter()
                .map(|preset| SharedString::from(preset.name.as_str()))
                .collect();
            app.presets = presets;
            window.set_export_presets(ModelRc::from(Rc::new(VecModel::from(names))));
            window.set_export_preset(-1);
            window.set_dialog_result(SharedString::default());
            window.set_dialog(SharedString::from("export"));
        });
    }
    {
        let app = Rc::clone(app);
        let handle = window.as_weak();
        window.on_run_export(move |preset, destination| {
            let Some(window) = handle.upgrade() else {
                return;
            };
            let mut app = app.borrow_mut();
            let Some(version) = usize::try_from(window.get_selected())
                .ok()
                .and_then(|i| app.items.get(i))
                .map(|item| item.version_id)
            else {
                window.set_dialog_result(SharedString::from("Select a photo first."));
                return;
            };
            if destination.is_empty() {
                window.set_dialog_result(SharedString::from("Enter a destination folder."));
                return;
            }
            let destination = Path::new(destination.as_str());
            let stored = usize::try_from(preset)
                .ok()
                .and_then(|i| app.presets.get(i))
                .map(|preset| preset.preset);
            let report = match stored {
                Some(id) => app
                    .library
                    .export_with_preset(&[version], id, destination, |_, _| {}),
                None => app.library.export_batch(
                    &[version],
                    &ExportSettings::default(),
                    destination,
                    |_, _| {},
                ),
            };
            window.set_dialog_result(SharedString::from(match report {
                Ok(report) => export_summary(&report),
                Err(error) => format!("Export failed: {error}"),
            }));
        });
    }
}

/// Connects the collections sidebar and its creation dialog.
fn wire_collections(app: &Rc<RefCell<App>>, window: &StudioWindow) {
    {
        let app = Rc::clone(app);
        let handle = window.as_weak();
        window.on_select_collection(move |index| {
            let Some(window) = handle.upgrade() else {
                return;
            };
            let mut app = app.borrow_mut();
            let picked = usize::try_from(index)
                .ok()
                .and_then(|i| app.collections.get(i))
                .copied();
            window.set_active_collection(if picked.is_some() { index } else { -1 });
            app.query.collection = picked;
            if let Err(error) = reload(&mut app, &window) {
                report_error(&window, &error);
            }
        });
    }
    {
        let app = Rc::clone(app);
        let handle = window.as_weak();
        window.on_run_new_collection(move |name| {
            let Some(window) = handle.upgrade() else {
                return;
            };
            let name = name.trim();
            if name.is_empty() {
                window.set_dialog_result(SharedString::from("Enter a name."));
                return;
            }
            let mut app = app.borrow_mut();
            let created = app
                .library
                .catalog_mut()
                .create_collection(None, name)
                .map_err(|e| e.to_string())
                .and_then(|_| refresh_collections(&mut app, &window));
            match created {
                Ok(()) => window.set_dialog(SharedString::default()),
                Err(error) => window
                    .set_dialog_result(SharedString::from(format!("Creation failed: {error}"))),
            }
        });
    }
    {
        let app = Rc::clone(app);
        let handle = window.as_weak();
        window.on_add_to_collection(move || {
            if let Some(window) = handle.upgrade() {
                collection_membership(&mut app.borrow_mut(), &window, true);
            }
        });
    }
    {
        let app = Rc::clone(app);
        let handle = window.as_weak();
        window.on_remove_from_collection(move || {
            if let Some(window) = handle.upgrade() {
                collection_membership(&mut app.borrow_mut(), &window, false);
            }
        });
    }
}

/// Adds the selected photo's version to the active collection, or removes
/// it, then reloads the grid (membership may change what it shows).
fn collection_membership(app: &mut App, window: &StudioWindow, add: bool) {
    let Some(collection) = usize::try_from(window.get_active_collection())
        .ok()
        .and_then(|i| app.collections.get(i))
        .copied()
    else {
        report_error(window, "select a collection in the sidebar first");
        return;
    };
    let Some(version) = usize::try_from(window.get_selected())
        .ok()
        .and_then(|i| app.items.get(i))
        .map(|item| item.version_id)
    else {
        return;
    };
    let catalog = app.library.catalog_mut();
    let changed = if add {
        catalog.add_to_collection(collection, &[version])
    } else {
        catalog.remove_from_collection(collection, &[version])
    };
    if let Err(error) = changed
        .map_err(|e| e.to_string())
        .and_then(|()| reload(app, window))
    {
        report_error(window, &error);
    }
}

/// Reloads the sidebar from the catalog's collection tree.
fn refresh_collections(app: &mut App, window: &StudioWindow) -> Result<(), String> {
    let tree = app
        .library
        .catalog()
        .collections()
        .map_err(|e| e.to_string())?;
    let mut flat = Vec::new();
    flatten_collections(&tree, 0, &mut flat);
    app.collections = flat.iter().map(|(id, ..)| *id).collect();
    let rows: Vec<ui::CollectionRow> = flat
        .into_iter()
        .map(|(_, name, depth, smart)| ui::CollectionRow {
            name: SharedString::from(name),
            depth,
            smart,
        })
        .collect();
    window.set_collections(ModelRc::from(Rc::new(VecModel::from(rows))));
    Ok(())
}

/// Flattens the collection tree into `(id, name, depth, smart)` sidebar
/// rows, depth first, children under their parent.
fn flatten_collections(
    nodes: &[CollectionNode],
    depth: i32,
    out: &mut Vec<(CollectionId, String, i32, bool)>,
) {
    for node in nodes {
        out.push((
            node.collection,
            node.name.clone(),
            depth,
            node.collection_type == CollectionType::Smart,
        ));
        flatten_collections(&node.children, depth + 1, out);
    }
}

/// One line summing up an import batch for the dialog.
fn import_summary(imported: usize, skipped: &[SkippedFile]) -> String {
    match skipped {
        [] => format!("{imported} imported."),
        [first, ..] => format!(
            "{imported} imported, {} skipped ({}).",
            skipped.len(),
            first.reason
        ),
    }
}

/// One line summing up an export batch for the dialog.
fn export_summary(report: &ExportReport) -> String {
    match (report.exported.first(), report.failed.first()) {
        (Some(done), _) => format!("Exported to {}.", done.path.display()),
        (None, Some(failed)) => format!("Export failed: {}", failed.reason),
        (None, None) => "Nothing to export.".to_owned(),
    }
}

/// Moves the develop head one revision back or forward, then refreshes.
fn history_step(app: &mut App, window: &StudioWindow, undo: bool) {
    let Some((_, version)) = app.develop else {
        return;
    };
    let moved = (|| {
        let mut session = app.library.edit(version)?;
        if undo { session.undo() } else { session.redo() }
    })();
    if let Err(error) = moved
        .map_err(|e| e.to_string())
        .and_then(|_| refresh_develop(app, window))
    {
        report_error(window, &error);
    }
}

/// Renders the develop preview at the head settings and mirrors those
/// settings into the sliders.
fn refresh_develop(app: &mut App, window: &StudioWindow) -> Result<(), String> {
    let Some((asset, version)) = app.develop else {
        return Ok(());
    };
    let settings = {
        let session = app.library.edit(version).map_err(|e| e.to_string())?;
        session.settings().clone()
    };
    window.set_dev(dev_model(&settings));
    let file = app
        .library
        .preview(asset, PreviewKind::Small)
        .map_err(|e| e.to_string())?;
    let image = slint::Image::load_from_path(&file.path)
        .map_err(|_| format!("cannot load preview {}", file.path.display()))?;
    window.set_develop_image(image);
    Ok(())
}

/// Mirrors pipeline settings into the develop slider model.
fn dev_model(settings: &Settings) -> ui::DevSettings {
    let wb = settings.white_balance.clone().unwrap_or_default();
    let crop = settings.crop.clone().unwrap_or(leyline_sdk::Crop {
        x: 0.0,
        y: 0.0,
        width: 1.0,
        height: 1.0,
    });
    ui::DevSettings {
        exposure: settings.exposure as f32,
        contrast: settings.contrast as f32,
        highlights: settings.highlights as f32,
        shadows: settings.shadows as f32,
        whites: settings.whites as f32,
        blacks: settings.blacks as f32,
        vibrance: settings.vibrance as f32,
        saturation: settings.saturation as f32,
        wb_temp: wb.temperature as f32,
        wb_tint: wb.tint as f32,
        rotation: settings.rotation as f32,
        crop_left: (crop.x * 100.0) as f32,
        crop_top: (crop.y * 100.0) as f32,
        crop_width: (crop.width * 100.0) as f32,
        crop_height: (crop.height * 100.0) as f32,
        nr_luminance: settings.noise_reduction.luminance as f32,
        nr_color: settings.noise_reduction.color as f32,
        sharpen_amount: settings.sharpening.amount as f32,
        sharpen_radius: settings.sharpening.radius as f32,
    }
}

/// Surfaces a callback failure in the status line, where a GUI user can
/// see it; stderr keeps a copy for terminal logs.
fn report_error(window: &StudioWindow, message: &str) {
    eprintln!("error: {message}");
    window.set_status_line(SharedString::from(format!("Error: {message}")));
}

/// Re-runs the grid query and rebuilds the cell model, keeping the current
/// selection when the same version is still visible.
fn reload(app: &mut App, window: &StudioWindow) -> Result<(), String> {
    let keep: Option<VersionId> = usize::try_from(window.get_selected())
        .ok()
        .and_then(|i| app.items.get(i))
        .map(|item| item.version_id);

    let total = app
        .library
        .catalog()
        .count(&app.query)
        .map_err(|e| e.to_string())?;
    let items = app
        .library
        .catalog()
        .grid(&app.query)
        .map_err(|e| e.to_string())?;

    // Only thumbnails already cached are loaded here, so the grid appears
    // instantly; the rest are queued and rendered by the thumbnail timer.
    let mut cells = Vec::with_capacity(items.len());
    let mut pending = VecDeque::new();
    for (index, item) in items.iter().enumerate() {
        let thumbnail = app
            .library
            .cached_preview(item.asset_id, PreviewKind::Thumbnail)
            .ok()
            .flatten()
            .and_then(|file| slint::Image::load_from_path(&file.path).ok());
        if thumbnail.is_none() {
            pending.push_back(index);
        }
        cells.push(Cell {
            thumbnail: thumbnail.unwrap_or_default(),
            filename: SharedString::from(item.filename.as_str()),
            stars: SharedString::from(format::stars(item.rating)),
            label: label_color(item.color_label),
            has_label: item.color_label.is_some(),
        });
    }
    app.items = items;
    app.pending = pending;
    app.cells = Rc::new(VecModel::from(cells));

    window.set_cells(ModelRc::from(Rc::clone(&app.cells)));
    window.set_status_line(SharedString::from(status_line(app.items.len(), total)));

    let selected = keep
        .and_then(|version| app.items.iter().position(|item| item.version_id == version))
        .and_then(|i| i32::try_from(i).ok())
        .unwrap_or(-1);
    window.set_selected(selected);
    if selected >= 0 {
        show_details(app, window, selected);
    }
    Ok(())
}

/// Reads and formats everything the side panel shows for one grid row.
fn show_details(app: &App, window: &StudioWindow, index: i32) {
    let Some(item) = usize::try_from(index).ok().and_then(|i| app.items.get(i)) else {
        return;
    };
    let details = match app.library.catalog().asset_details(item.asset_id) {
        Ok(details) => details,
        Err(error) => {
            eprintln!("error: {error}");
            return;
        }
    };
    let meta = details.metadata.as_ref();
    window.set_detail_filename(SharedString::from(details.filename.as_str()));
    window.set_detail_path(SharedString::from(details.relative_path.as_str()));
    window.set_detail_capture(SharedString::from(
        details
            .capture_date
            .map_or_else(|| "—".to_owned(), format::capture_date),
    ));
    window.set_detail_dimensions(SharedString::from(format::dimensions(
        details.width,
        details.height,
    )));
    window.set_detail_file_size(SharedString::from(format::file_size(details.file_size)));
    window.set_detail_camera(SharedString::from(
        meta.and_then(|m| m.camera.as_ref()).map_or_else(
            || "—".to_owned(),
            |c| format!("{} {}", c.manufacturer, c.model),
        ),
    ));
    window.set_detail_lens(SharedString::from(
        meta.and_then(|m| m.lens.as_ref()).map_or_else(
            || "—".to_owned(),
            |l| format!("{} {}", l.manufacturer, l.model),
        ),
    ));
    window.set_detail_exposure(SharedString::from(
        meta.map_or_else(String::new, format::exposure_line),
    ));
}

/// The header line above the grid.
fn status_line(shown: usize, total: u64) -> String {
    if shown as u64 >= total {
        format!("{total} photos")
    } else {
        format!("{shown} of {total} photos")
    }
}

/// The label shown on the sort button for a sort order.
fn sort_label(sort: Sort) -> &'static str {
    SORTS
        .iter()
        .find(|(candidate, _)| *candidate == sort)
        .map_or(SORTS[0].1, |(_, label)| label)
}

/// The dot color of a catalog color label.
fn label_color(label: Option<ColorLabel>) -> slint::Color {
    match label {
        Some(ColorLabel::Red) => slint::Color::from_rgb_u8(0xE0, 0x4F, 0x4F),
        Some(ColorLabel::Yellow) => slint::Color::from_rgb_u8(0xE0, 0xC0, 0x4F),
        Some(ColorLabel::Green) => slint::Color::from_rgb_u8(0x6F, 0xBF, 0x6F),
        Some(ColorLabel::Blue) => slint::Color::from_rgb_u8(0x5F, 0x8F, 0xDF),
        Some(ColorLabel::Purple) => slint::Color::from_rgb_u8(0xA0, 0x6F, 0xDF),
        None => slint::Color::default(),
    }
}

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use leyline_sdk::{ExportedVersion, FailedExport};

    use super::*;

    #[test]
    fn import_summaries_count_and_explain() {
        assert_eq!(import_summary(3, &[]), "3 imported.");
        let skipped = vec![
            SkippedFile {
                path: PathBuf::from("/photos/a.xmp"),
                reason: "unsupported file type".to_owned(),
            },
            SkippedFile {
                path: PathBuf::from("/photos/b.xmp"),
                reason: "unsupported file type".to_owned(),
            },
        ];
        assert_eq!(
            import_summary(1, &skipped),
            "1 imported, 2 skipped (unsupported file type)."
        );
    }

    #[test]
    fn flattening_keeps_children_under_their_parent() {
        let node = |id: i64, name: &str, children: Vec<CollectionNode>| CollectionNode {
            collection: CollectionId::new(id),
            name: name.to_owned(),
            description: None,
            collection_type: CollectionType::Manual,
            children,
        };
        let tree = vec![
            node(1, "Travel", vec![node(2, "Iceland", vec![])]),
            node(3, "Portfolio", vec![]),
        ];
        let mut flat = Vec::new();
        flatten_collections(&tree, 0, &mut flat);
        let shape: Vec<(i64, &str, i32)> = flat
            .iter()
            .map(|(id, name, depth, _)| (id.get(), name.as_str(), *depth))
            .collect();
        assert_eq!(
            shape,
            vec![(1, "Travel", 0), (2, "Iceland", 1), (3, "Portfolio", 0)]
        );
    }

    #[test]
    fn export_summaries_show_the_file_or_the_failure() {
        let mut report = ExportReport::default();
        assert_eq!(export_summary(&report), "Nothing to export.");
        report.failed.push(FailedExport {
            version: VersionId::new(7),
            reason: "no such version".to_owned(),
        });
        assert_eq!(export_summary(&report), "Export failed: no such version");
        report.exported.push(ExportedVersion {
            version: VersionId::new(7),
            path: PathBuf::from("/out/photo.jpg"),
        });
        assert_eq!(export_summary(&report), "Exported to /out/photo.jpg.");
    }
}
