//! Leyline Studio desktop application (`docs/roadmap.md` phase 5).
//!
//! The library browser. Studio opens a library through the SDK — never the
//! catalog directly — renders the photo grid with cached thumbnails, lets
//! the user filter, sort and classify (rate, label, flag) photos, shows
//! the metadata and keywords of the selected photo (tagging by
//! slash-separated path), and develops it non-destructively in a
//! dedicated view (`D` enters, `G` leaves).

// Without this, Windows links the GUI subsystem's exe as a console
// application: launching it allocates a console window alongside the
// Slint window, and that console is what's actually hosting the process —
// closing it kills Studio along with it. `windows_subsystem = "windows"`
// tells the linker not to allocate one. Kept debug-only-console via
// `cfg_attr` so a local `cargo run` on Windows still shows `eprintln!`
// output (`report_error`) in a terminal while developing; the shipped
// release build (what `packaging/windows/build-nsis.sh` produces) never
// gets a console. No-op on non-Windows targets.
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

mod app;
mod classify;
mod develop;
mod events;
mod format;
mod library;
mod map_view;
mod masks;
mod models;
mod preferences;
mod updates;
mod wiring;

/// UI generated by `slint-build` from `ui/studio.slint`.
#[allow(missing_docs, clippy::all)]
mod ui {
    slint::include_modules!();
}

use std::cell::RefCell;
use std::collections::{HashSet, VecDeque};
use std::path::{Path, PathBuf};
use std::rc::Rc;
use std::sync::{Arc, Mutex};

use leyline_sdk::{ColorLabel, GridQuery, Library};
use slint::winit_030::WinitWindowAccessor;
use slint::{ComponentHandle, Global, ModelRc, SharedString, VecModel};

use app::App;
use app::{report_error, window_is_stale};
use events::event_pump;
use library::{
    default_library_dir, load_recent_libraries, open_or_create_library, recent_libraries_path,
    record_recent_library, save_recent_libraries,
};
use models::{label_color, sort_label};
use preferences::{PreferencesFile, preferences_path, record_launch};
use ui::{FilterState, GridState, LibraryState, StudioWindow};
use wiring::collections::{refresh_collections, wire_collection_management, wire_collections};
use wiring::confirm::wire_confirm;
use wiring::develop::clipboard::wire_settings_clipboard;
use wiring::develop::wire_develop;
use wiring::dialogs::preferences::{
    apply_startup_language, ask_consent_if_due, schedule_startup_check, wire_preferences,
};
use wiring::dialogs::wire_dialogs;
use wiring::filters::{refresh_shot_facets, wire_classify, wire_filters};
use wiring::folders::{refresh_folders, wire_folders};
use wiring::grid::{load_window, reload, wire_select};
use wiring::keywords::wire_keywords;
use wiring::library::{wire_culling, wire_library, wire_processors};
use wiring::map::wire_map;
use wiring::pairs::wire_pairs;
use wiring::presets::{refresh_presets, wire_presets};
use wiring::removal::wire_removal;
use wiring::tether::wire_tether;
use wiring::views::wire_views;

/// The bundled-translation language to try at startup (ADR 0019): the
/// primary subtag of the system locale (`fr_FR.UTF-8` → `fr`, `en-US` →
/// `en`), lowercased to match the `translations/<lang>/` directory names
/// `slint_build::with_bundled_translations` bundles from.
fn system_language() -> Option<String> {
    let locale = sys_locale::get_locale()?;
    let primary = locale.split(['-', '_']).next().unwrap_or(&locale);
    Some(primary.to_lowercase())
}

/// The size [`size_window_to_screen`] aims for when two thirds of the screen
/// would be smaller, in logical pixels — the room the interface wants once
/// the side panels have folded (`studio.slint`, `narrow-threshold`).
///
/// A floor on the *wish*, not on the result: a screen too small to hold it
/// gets a window that fits the screen instead, because a window larger than
/// the display is worse than a cramped one.
const MIN_WINDOW_WIDTH: f32 = 900.0;
const MIN_WINDOW_HEIGHT: f32 = 600.0;

/// The width below which `studio.slint` folds the side panels away
/// (`narrow-threshold`). Mirrored here so the initial size can clear it.
///
/// The two must be changed together: this one decides whether the window
/// *starts* wide enough to show the panels, that one decides whether they
/// are shown at any given width.
const PANELS_THRESHOLD: f32 = 1340.0;

/// How much of the screen a window may occupy at startup.
///
/// The desktop keeps some of the screen for itself — a taskbar, a dock, a
/// panel — and the window manager adds a title bar on top of whatever size
/// is asked for. winit reports the monitor's full size and no work area, so
/// this is a proportion rather than a measurement: enough to keep the window
/// clear of the furniture on every desktop tried, without pretending to know
/// where that furniture is.
const USABLE_FRACTION_WIDTH: f32 = 0.94;
const USABLE_FRACTION_HEIGHT: f32 = 0.88;

/// Resizes and centers the window at roughly two thirds of the primary
/// monitor's resolution, instead of the fixed `preferred-width` /
/// `preferred-height` `studio.slint`'s `StudioWindow` declares (kept there
/// as the fallback size — see the call site in [`run`]).
///
/// The winit window backing a Slint window is created lazily once the event
/// loop starts (not at `StudioWindow::new()` time), so this only has
/// anything to act on once called from a `slint::spawn_local` future — see
/// the call site. If no winit window exists yet, or no monitor can be
/// identified (headless environment, an unsupported platform, or a
/// windowing system such as Wayland that doesn't report a primary monitor),
/// this is a no-op and the `.slint` fallback size stands unchanged.
/// The window size to open at on a screen of this logical size.
///
/// Two thirds of the screen is the *wish*; what fits is the rule. The order
/// of the clamps is the whole point:
///
/// 1. two thirds of the screen, which is the shape wanted on a large one;
/// 2. raised to [`MIN_WINDOW_WIDTH`]/[`MIN_WINDOW_HEIGHT`], the room the
///    interface wants once its side panels have folded;
/// 3. **lowered to what the screen can actually show**, which is applied
///    last and therefore always wins.
///
/// Step 3 is what was missing. `.max(MIN)` alone *raised* the size on a
/// small screen instead of lowering it: on a 1366x768 laptop two thirds
/// gives 911x512, which the old floor of 1024x700 pushed back up to a window
/// taller than the space left once the title bar and the taskbar have taken
/// theirs.
///
/// Step 4 pulls the other way, and only when there is room: open wide enough
/// for the side panels whenever the screen can afford them. Two thirds of
/// 1920 is 1280, which is *under* [`PANELS_THRESHOLD`] — without this the
/// commonest desktop screen there is would start with its panels folded, and
/// folding is meant to be what a small screen forces, never what a large one
/// chooses.
///
/// Split out from [`size_window_to_screen`] so it can be tested without a
/// monitor, which is the only part of that function a test can reach.
fn startup_size(logical_width: f32, logical_height: f32) -> (f32, f32) {
    let usable_width = logical_width * USABLE_FRACTION_WIDTH;
    let usable_height = logical_height * USABLE_FRACTION_HEIGHT;

    let mut width = (logical_width * 2.0 / 3.0)
        .max(MIN_WINDOW_WIDTH)
        .min(usable_width);
    let height = (logical_height * 2.0 / 3.0)
        .max(MIN_WINDOW_HEIGHT)
        .min(usable_height);

    if usable_width >= PANELS_THRESHOLD {
        width = width.max(PANELS_THRESHOLD);
    }
    (width, height)
}

fn size_window_to_screen(window: &StudioWindow) {
    let win = window.window();
    win.with_winit_window(|winit_window| {
        let Some(monitor) = winit_window
            .primary_monitor()
            .or_else(|| winit_window.current_monitor())
        else {
            return;
        };
        let scale = monitor.scale_factor() as f32;
        let monitor_size = monitor.size();
        let logical_width = monitor_size.width as f32 / scale;
        let logical_height = monitor_size.height as f32 / scale;
        let (target_width, target_height) = startup_size(logical_width, logical_height);
        win.set_size(slint::LogicalSize::new(target_width, target_height));

        // Center on the monitor: convert the just-chosen logical size back
        // to physical pixels to match `monitor.size()`/`monitor.position()`,
        // which are always physical.
        let monitor_position = monitor.position();
        let target_physical_width = (target_width * scale) as i32;
        let target_physical_height = (target_height * scale) as i32;
        let x = monitor_position.x + (monitor_size.width as i32 - target_physical_width) / 2;
        let y = monitor_position.y + (monitor_size.height as i32 - target_physical_height) / 2;
        win.set_position(slint::PhysicalPosition::new(x, y));
    });
}

fn main() -> std::process::ExitCode {
    match run() {
        Ok(()) => std::process::ExitCode::SUCCESS,
        Err(message) => {
            eprintln!("error: {message}");
            std::process::ExitCode::FAILURE
        }
    }
}

fn run() -> Result<(), String> {
    // No argument: this is how a GUI shortcut launches Studio (the Windows
    // installer's Start Menu entry, the Linux AppImage, double-clicking the
    // macOS .app) — none of those attach a console, so the old
    // `Err("usage: ...")` here used to look like a silent, instant crash.
    // Fall back to a sensible per-OS default location instead; an explicit
    // `leyline-studio <library-dir>` argument (scripts, the CLI test
    // harness, an existing user's shortcut) still behaves exactly as before.
    let library = match std::env::args().nth(1) {
        Some(root) => Library::open(Path::new(&root)).map_err(|e| e.to_string())?,
        None => open_or_create_library(&default_library_dir()?)?,
    };
    // Preferences (ADR 0078 §5), read before anything is on screen: the
    // language they may carry has to be applied at the window's first
    // paint, and the launch counter they hold decides whether the consent
    // question of §4 is due. A config directory that cannot be read or
    // written is not a reason to refuse to start — every failure here
    // lands on the defaults, and every default is offline.
    let preferences = Arc::new(Mutex::new(PreferencesFile::open(preferences_path()?)));
    if let Ok(mut file) = preferences.lock() {
        let _ = file.update(record_launch);
    }

    let info = library.catalog().library().map_err(|e| e.to_string())?;
    let library_path = library.root().display().to_string();
    let events = library.subscribe();

    // "Open Recent" (File menu): record this library, then keep the rest of
    // the list (the ones other than the one we're opening right now) around
    // for the callback below to relaunch into. A failure to read/write this
    // file is never fatal to opening the library itself.
    let recent_path = recent_libraries_path()?;
    let recent_libraries =
        record_recent_library(&load_recent_libraries(&recent_path), library.root());
    save_recent_libraries(&recent_path, &recent_libraries)?;
    let other_recent_libraries: Vec<PathBuf> = recent_libraries
        .iter()
        .filter(|p| p.as_path() != library.root())
        .cloned()
        .collect();

    let app = Rc::new(RefCell::new(App {
        library,
        query: GridQuery::default(),
        items: Vec::new(),
        window_start: 0,
        total: 0,
        viewport: (0, 0),
        multi_selected: std::collections::BTreeSet::new(),
        pending_confirm: None,
        loupe_pending: None,
        develop: None,
        dev_before: None,
        soft_proof: None,
        // On by default: a mask one cannot see is the state ADR 0071 fixes.
        dev_versions: Vec::new(),
        show_mask_overlay: true,
        clip_highlights: false,
        clip_shadows: false,
        keystone: Vec::new(),
        last_live_render: None,
        dev_clipboard: None,
        dev_history: Vec::new(),
        dev_history_version: None,
        presets: Vec::new(),
        dev_pixels: None,
        print_presets: Vec::new(),
        sheet_presets: Vec::new(),
        dev_presets: Vec::new(),
        preset_folders: Vec::new(),
        preset_rows: Vec::new(),
        preset_expanded: wiring::presets::default_expanded(),
        preset_filter: String::new(),
        preset_trial: slint::Timer::default(),
        collections: Vec::new(),
        collection_depths: Vec::new(),
        move_targets: Vec::new(),
        folders: Vec::new(),
        compare_candidate: None,
        survey: Vec::new(),
        keywords: Vec::new(),
        keyword_filter: None,
        cells: Rc::new(VecModel::default()),
        pending: VecDeque::new(),
        events,
        import_job: None,
        scan_job: None,
        candidates: Vec::new(),
        candidate_source: std::path::PathBuf::new(),
        export_job: None,
        print_job: None,
        sheet_job: None,
        derive_job: None,
        cull_job: None,
        proposal: None,
        preview_jobs: HashSet::new(),
        tether_connected: false,
        profile_thumbs_for: None,
        profile_paths: Vec::new(),
        tether_presets: Vec::new(),
        tether_preset: None,
        tether_captured: 0,
        watch_active: false,
        watch_imported: 0,
        map: None,
        map_canvas: (map_view::DEFAULT_WIDTH, map_view::DEFAULT_HEIGHT),
    }));

    let window = StudioWindow::new().map_err(|e| e.to_string())?;
    // ADR 0019: system locale first, English fallback — and, since
    // ADR 0078 §3, a stored preference ahead of both. `select_bundled_translation`
    // must run after `StudioWindow::new()` — the bundled language list is
    // registered by the generated component's constructor — and an
    // unmatched or undetectable locale simply keeps the English strings
    // `@tr(...)` is written in, so a failed lookup is not an error to surface.
    apply_startup_language(&preferences, system_language().as_deref());
    LibraryState::get(&window).set_library_name(SharedString::from(info.name.as_str()));
    // Surfaced in Help ▸ About Leyline (ADR 0020): the no-argument fallback
    // picks a real, disk-backed location on the user's behalf, so it must
    // stay discoverable — nobody should have to guess where their catalog
    // ended up. An explicit argument is just as worth showing here.
    LibraryState::get(&window).set_library_path(SharedString::from(library_path.as_str()));
    let recent_library_names: Vec<SharedString> = other_recent_libraries
        .iter()
        .map(|p| SharedString::from(p.display().to_string()))
        .collect();
    LibraryState::get(&window)
        .set_recent_libraries(ModelRc::from(Rc::new(VecModel::from(recent_library_names))));
    // Surfaced in Help ▸ About Leyline: build-time constant from Cargo.toml's
    // `version.workspace = true`, so it stays in sync without a manual edit.
    LibraryState::get(&window).set_app_version(SharedString::from(env!("CARGO_PKG_VERSION")));
    // Recorded by `build.rs`; every field degrades to "inconnu" rather than
    // failing a build made from a source tarball with no git checkout.
    // The decoder line is read at run time, unlike the four build-time
    // constants around it, and that difference is the point: LibRaw is linked
    // dynamically (ADR 0004), so it is a property of this machine rather than
    // of this build. `docs/pipeline.md` §5.1 counts it among the terms of the
    // bit-for-bit promise (ADR 0086), which makes it the one fact about a
    // render a user cannot otherwise discover — and the first one worth having
    // in a report that says the pixels changed.
    LibraryState::get(&window).set_build_details(SharedString::from(format!(
        "Version {}\nCommit {}\nTarget {}\n{}\nLibRaw {}",
        env!("CARGO_PKG_VERSION"),
        env!("LEYLINE_COMMIT"),
        env!("LEYLINE_TARGET"),
        env!("LEYLINE_RUSTC"),
        leyline_sdk::decoder_version(),
    )));
    FilterState::get(&window).set_filter_label(-1);
    FilterState::get(&window).set_filter_pick(-1);
    FilterState::get(&window)
        .set_sort_label(SharedString::from(sort_label(GridQuery::default().sort)));
    let palette: Vec<slint::Color> = (0..5)
        .filter_map(ColorLabel::from_i64)
        .map(|label| label_color(Some(label)))
        .collect();
    FilterState::get(&window).set_label_colors(ModelRc::from(Rc::new(VecModel::from(palette))));

    {
        let mut app = app.borrow_mut();
        refresh_collections(&mut app, &window)?;
        refresh_folders(&mut app, &window)?;
        refresh_presets(&mut app, &window)?;
        refresh_shot_facets(&app, &window)?;
        reload(&mut app, &window)?;
    }

    wire_select(&app, &window);
    wire_classify(&app, &window);
    wire_removal(&app, &window);
    wire_pairs(&app, &window);
    wire_confirm(&app, &window);
    wire_settings_clipboard(&app, &window);
    wire_filters(&app, &window);
    wire_develop(&app, &window);
    wire_library(&window, other_recent_libraries);
    wire_processors(&app, &window);
    wire_culling(&app, &window);
    wire_dialogs(&app, &window);
    wire_preferences(&window, &preferences);
    wire_collections(&app, &window);
    wire_collection_management(&app, &window);
    wire_folders(&app, &window);
    wire_keywords(&app, &window);
    wire_presets(&app, &window);
    wire_map(&app, &window);
    wire_tether(&app, &window);
    wire_views(&app, &window);
    {
        // Scrolling or resizing moves the visible window: fetch the matching
        // rows from the catalog when the loaded window no longer covers it.
        let app = Rc::clone(&app);
        let handle = window.as_weak();
        GridState::get(&window).on_viewport_moved(move |first, capacity| {
            let Some(window) = handle.upgrade() else {
                return;
            };
            let mut app = app.borrow_mut();
            app.viewport = (
                usize::try_from(first).unwrap_or(0),
                usize::try_from(capacity).unwrap_or(0).max(1),
            );
            let loaded = app.window_start..app.window_start + app.items.len();
            if window_is_stale(app.viewport, &loaded, app.total)
                && let Err(error) = load_window(&mut app, &window)
            {
                report_error(&window, &error);
            }
        });
    }
    // Kept alive until the event loop ends: dropping the timer stops it.
    let _events = event_pump(&app, &window);

    // The second-launch question, and the one automatic update check of
    // this launch (ADR 0078 §4, ADR 0077 §2). Both are no-ops until
    // someone has answered, and the check is a no-op unless the answer was
    // yes and the last successful one is a day old.
    ask_consent_if_due(&window, &preferences);
    schedule_startup_check(&window, &preferences);

    // The winit window (and with it, monitor info) only exists once the
    // event loop is running — see `size_window_to_screen`'s doc comment —
    // so this is scheduled as a one-shot future rather than called
    // directly here. It runs once, at the very start of `run()` below,
    // before the window is ever presented to the user.
    {
        let handle = window.as_weak();
        slint::spawn_local(async move {
            if let Some(window) = handle.upgrade() {
                size_window_to_screen(&window);
            }
        })
        .map_err(|e| e.to_string())?;
    }

    window.run().map_err(|e| e.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Every screen a window may open on must get a window that fits it.
    ///
    /// The table is the one measured on real Xvfb screens on 2026-08-29,
    /// after the fix; before it, the first three rows produced a 1024x700
    /// window — taller than a 720-pixel screen has left once the desktop's
    /// own furniture is out.
    #[test]
    fn the_window_never_opens_larger_than_the_screen() {
        for (screen_w, screen_h) in [
            (1024.0, 768.0),
            (1280.0, 720.0),
            (1366.0, 768.0),
            (1600.0, 900.0),
            (1920.0, 1080.0),
            (2560.0, 1440.0),
            (3840.0, 2160.0),
        ] {
            let (w, h) = startup_size(screen_w, screen_h);
            assert!(
                w <= screen_w * USABLE_FRACTION_WIDTH,
                "{screen_w}x{screen_h}: width {w} exceeds the usable width"
            );
            assert!(
                h <= screen_h * USABLE_FRACTION_HEIGHT,
                "{screen_w}x{screen_h}: height {h} exceeds the usable height"
            );
        }
    }

    /// The floor is a wish, not a guarantee: a screen too small to hold it
    /// gets a window that fits instead of one that overflows.
    #[test]
    fn a_screen_smaller_than_the_floor_still_gets_a_window_that_fits() {
        let (w, h) = startup_size(800.0, 600.0);
        // It fits, which is the rule.
        assert_eq!(w, 800.0 * USABLE_FRACTION_WIDTH);
        assert_eq!(h, 600.0 * USABLE_FRACTION_HEIGHT);
        // And it is therefore below the floor, which is the wish. Asserted
        // separately rather than joined with `&&`: on this screen the second
        // follows from the first, and writing it as one condition says the
        // floor was tested when it was not.
        assert!(w < MIN_WINDOW_WIDTH);
        assert!(h < MIN_WINDOW_HEIGHT);
    }

    /// A screen with room for the side panels opens with room for them, so
    /// folding stays something a small screen forces rather than something a
    /// large one chooses.
    #[test]
    fn a_roomy_screen_opens_wide_enough_for_the_side_panels() {
        for (screen_w, screen_h) in [(1600.0, 900.0), (1920.0, 1080.0), (2560.0, 1440.0)] {
            let (w, _) = startup_size(screen_w, screen_h);
            assert!(
                w >= PANELS_THRESHOLD,
                "{screen_w}x{screen_h}: {w} would start with the panels folded"
            );
        }
    }

    /// And a screen without that room does not pretend to have it.
    #[test]
    fn a_cramped_screen_opens_folded_rather_than_overflowing() {
        for (screen_w, screen_h) in [(1280.0, 720.0), (1366.0, 768.0)] {
            let (w, _) = startup_size(screen_w, screen_h);
            assert!(
                w < PANELS_THRESHOLD,
                "{screen_w}x{screen_h}: {w} claims room the screen has not got"
            );
        }
    }
}
