//! Leyline Studio desktop application (`docs/roadmap.md` phase 5).
//!
//! The library browser. Studio opens a library through the SDK — never the
//! catalog directly — renders the photo grid with cached thumbnails, lets
//! the user filter, sort and classify (rate, label, flag) photos, shows
//! the metadata and keywords of the selected photo (tagging by
//! slash-separated path), and develops it non-destructively in a
//! dedicated view (`D` enters, `G` leaves).

mod classify;
mod develop;
mod format;

/// UI generated by `slint-build` from `ui/studio.slint`.
#[allow(missing_docs, clippy::all)]
mod ui {
    slint::include_modules!();
}

use std::cell::RefCell;
use std::collections::{HashSet, VecDeque};
use std::path::{Path, PathBuf};
use std::rc::Rc;
use std::time::Duration;

use classify::Action;
use leyline_sdk::{
    AssetId, CollectionId, CollectionNode, CollectionType, ColorLabel, Event, ExportFormat,
    ExportPreset, ExportReport, ExportSettings, GridItem, GridQuery, ImportOptions, JobId,
    JobResult, KeywordId, KeywordNode, Library, PickState, Preset, PreviewKind, Settings,
    SettingsGroup, SkippedFile, Sort, VersionId,
};
use slint::{ComponentHandle, Global, Model, ModelRc, SharedString, Timer, TimerMode, VecModel};

use ui::{Cell, StudioWindow, Tr};

/// Sort orders the header button cycles through, with their labels.
const SORTS: [(Sort, &str); 8] = [
    (Sort::CaptureDate { ascending: false }, "capture ↓"),
    (Sort::CaptureDate { ascending: true }, "capture ↑"),
    (Sort::Filename { ascending: true }, "filename A–Z"),
    (Sort::Filename { ascending: false }, "filename Z–A"),
    (Sort::ImportedAt { ascending: false }, "imported ↓"),
    (Sort::ImportedAt { ascending: true }, "imported ↑"),
    (Sort::Rating { ascending: false }, "rating ↓"),
    (Sort::Rating { ascending: true }, "rating ↑"),
];

/// Cells kept loaded beyond each edge of the visible window; a new window
/// is fetched once the viewport gets within half this margin of an edge.
const OVERSCAN: usize = 48;

/// Application state shared by every UI callback.
struct App {
    library: Library,
    query: GridQuery,
    /// Rows of the loaded window, parallel to the grid cell model;
    /// `items[0]` is grid row `window_start` (virtual scrolling).
    items: Vec<GridItem>,
    /// Grid index of the first loaded row.
    window_start: usize,
    /// Total rows matching the query, loaded or not.
    total: u64,
    /// Last viewport reported by the UI: first visible cell, cell capacity.
    viewport: (usize, usize),
    /// The photo open in the develop view, when in develop mode.
    develop: Option<(AssetId, VersionId)>,
    /// Stored export presets, parallel to the dialog's preset chips.
    presets: Vec<ExportPreset>,
    /// Stored develop presets, parallel to the develop sidebar's rows.
    dev_presets: Vec<Preset>,
    /// Flattened collection ids, parallel to the sidebar rows.
    collections: Vec<CollectionId>,
    /// Keywords of the selected photo, parallel to the panel's rows.
    keywords: Vec<KeywordId>,
    /// The keyword the grid is filtered to, when one is active.
    keyword_filter: Option<KeywordId>,
    /// The live cell model, so thumbnails can be filled in row by row.
    cells: Rc<VecModel<Cell>>,
    /// Grid rows still waiting for a thumbnail, drained by the event pump.
    pending: VecDeque<usize>,
    /// Engine event stream, polled by the pump timer (Slint is
    /// single-threaded: pull, don't push across threads).
    events: std::sync::mpsc::Receiver<Event>,
    /// The import job the dialog is waiting on, when one runs.
    import_job: Option<JobId>,
    /// The export job the dialog is waiting on, when one runs.
    export_job: Option<JobId>,
    /// Thumbnail render jobs currently in flight.
    preview_jobs: HashSet<JobId>,
}

/// Thumbnail render jobs kept in flight at once: enough to hide latency,
/// few enough to leave the catalog responsive for the UI thread.
const MAX_PREVIEW_JOBS: usize = 3;

/// The bundled-translation language to try at startup (ADR 0019): the
/// primary subtag of the system locale (`fr_FR.UTF-8` → `fr`, `en-US` →
/// `en`), lowercased to match the `translations/<lang>/` directory names
/// `slint_build::with_bundled_translations` bundles from.
fn system_language() -> Option<String> {
    let locale = sys_locale::get_locale()?;
    let primary = locale.split(['-', '_']).next().unwrap_or(&locale);
    Some(primary.to_lowercase())
}

fn main() -> std::process::ExitCode {
    match run() {
        Ok(()) => std::process::ExitCode::SUCCESS,
        Err(message) => {
            eprintln!("error: {message}");
            std::process::ExitCode::FAILURE
        }
    }
}

fn run() -> Result<(), String> {
    let Some(root) = std::env::args().nth(1) else {
        return Err("usage: leyline-studio <library-dir>".to_owned());
    };
    let library = Library::open(Path::new(&root)).map_err(|e| e.to_string())?;
    let info = library.catalog().library().map_err(|e| e.to_string())?;
    let events = library.subscribe();

    let app = Rc::new(RefCell::new(App {
        library,
        query: GridQuery::default(),
        items: Vec::new(),
        window_start: 0,
        total: 0,
        viewport: (0, 0),
        develop: None,
        presets: Vec::new(),
        dev_presets: Vec::new(),
        collections: Vec::new(),
        keywords: Vec::new(),
        keyword_filter: None,
        cells: Rc::new(VecModel::default()),
        pending: VecDeque::new(),
        events,
        import_job: None,
        export_job: None,
        preview_jobs: HashSet::new(),
    }));

    let window = StudioWindow::new().map_err(|e| e.to_string())?;
    // ADR 0019: system locale first, English fallback. `select_bundled_translation`
    // must run after `StudioWindow::new()` — the bundled language list is
    // registered by the generated component's constructor — and an
    // unmatched or undetectable locale simply keeps the English strings
    // `@tr(...)` is written in, so a failed lookup is not an error to surface.
    if let Some(language) = system_language() {
        let _ = slint::select_bundled_translation(&language);
    }
    window.set_library_name(SharedString::from(info.name.as_str()));
    window.set_filter_label(-1);
    window.set_filter_pick(-1);
    window.set_sort_label(SharedString::from(sort_label(GridQuery::default().sort)));
    let palette: Vec<slint::Color> = (0..5)
        .filter_map(ColorLabel::from_i64)
        .map(|label| label_color(Some(label)))
        .collect();
    window.set_label_colors(ModelRc::from(Rc::new(VecModel::from(palette))));

    {
        let mut app = app.borrow_mut();
        refresh_collections(&mut app, &window)?;
        refresh_presets(&mut app, &window)?;
        reload(&mut app, &window)?;
    }

    wire_select(&app, &window);
    wire_classify(&app, &window);
    wire_filters(&app, &window);
    wire_develop(&app, &window);
    wire_dialogs(&app, &window);
    wire_collections(&app, &window);
    wire_keywords(&app, &window);
    wire_presets(&app, &window);
    {
        // Scrolling or resizing moves the visible window: fetch the matching
        // rows from the catalog when the loaded window no longer covers it.
        let app = Rc::clone(&app);
        let handle = window.as_weak();
        window.on_viewport_moved(move |first, capacity| {
            let Some(window) = handle.upgrade() else {
                return;
            };
            let mut app = app.borrow_mut();
            app.viewport = (
                usize::try_from(first).unwrap_or(0),
                usize::try_from(capacity).unwrap_or(0).max(1),
            );
            let loaded = app.window_start..app.window_start + app.items.len();
            if window_is_stale(app.viewport, &loaded, app.total)
                && let Err(error) = load_window(&mut app, &window)
            {
                report_error(&window, &error);
            }
        });
    }
    // Kept alive until the event loop ends: dropping the timer stops it.
    let _events = event_pump(&app, &window);

    window.run().map_err(|e| e.to_string())
}

/// Starts the timer that pumps engine events into the UI — job progress,
/// finished imports and exports, freshly rendered thumbnails — and keeps
/// a few thumbnail render jobs in flight off the UI thread.
fn event_pump(app: &Rc<RefCell<App>>, window: &StudioWindow) -> Timer {
    let app = Rc::clone(app);
    let handle = window.as_weak();
    let timer = Timer::default();
    timer.start(TimerMode::Repeated, Duration::from_millis(30), move || {
        let Some(window) = handle.upgrade() else {
            return;
        };
        let mut app = app.borrow_mut();
        while let Ok(event) = app.events.try_recv() {
            handle_event(&mut app, &window, event);
        }
        dispatch_thumbnails(&mut app);
    });
    timer
}

/// Reacts to one engine event on the UI thread.
fn handle_event(app: &mut App, window: &StudioWindow, event: Event) {
    match event {
        Event::PreviewReady {
            asset_id,
            kind: PreviewKind::Thumbnail,
        } => {
            set_thumbnail_cell(app, asset_id);
        }
        Event::JobProgress {
            job_id,
            done,
            total,
        } => {
            let done = i32::try_from(done).unwrap_or(i32::MAX);
            let total = i32::try_from(total).unwrap_or(i32::MAX);
            if app.import_job == Some(job_id) {
                window.set_dialog_result(Tr::get(window).invoke_importing_progress(done, total));
            } else if app.export_job == Some(job_id) {
                window.set_dialog_result(Tr::get(window).invoke_exporting_progress(done, total));
            }
        }
        Event::JobFinished { job_id, result } => {
            if app.import_job == Some(job_id) {
                app.import_job = None;
                window.set_dialog_result(match result {
                    JobResult::Import(report) => {
                        SharedString::from(import_summary(report.imported.len(), &report.skipped))
                    }
                    JobResult::Failed(reason) => {
                        Tr::get(window).invoke_import_failed(SharedString::from(reason))
                    }
                    _ => return,
                });
                if let Err(error) = reload(app, window) {
                    report_error(window, &error);
                }
            } else if app.export_job == Some(job_id) {
                app.export_job = None;
                window.set_dialog_result(match result {
                    JobResult::Export(report) => SharedString::from(export_summary(&report)),
                    JobResult::Failed(reason) => {
                        Tr::get(window).invoke_export_failed(SharedString::from(reason))
                    }
                    _ => return,
                });
            } else if app.preview_jobs.remove(&job_id)
                && let JobResult::Failed(reason) = result
            {
                eprintln!("error: {reason}");
            }
        }
        Event::AssetsChanged { asset_ids } => {
            // Another writer touched assets: refresh the side panel when
            // the selected photo is among them.
            let selected = window.get_selected();
            if let Some(asset) = item_at(app, selected).map(|item| item.asset_id)
                && asset_ids.contains(&asset)
            {
                show_details(app, window, selected);
            }
        }
        _ => {}
    }
}

/// Fills the grid cell of an asset with its freshly cached thumbnail.
fn set_thumbnail_cell(app: &mut App, asset: AssetId) {
    let Some(index) = app.items.iter().position(|item| item.asset_id == asset) else {
        return; // scrolled out of the loaded window meanwhile
    };
    let Ok(Some(file)) = app.library.cached_preview(asset, PreviewKind::Thumbnail) else {
        return;
    };
    let Ok(image) = slint::Image::load_from_path(&file.path) else {
        return;
    };
    if let Some(mut cell) = app.cells.row_data(index) {
        cell.thumbnail = image;
        app.cells.set_row_data(index, cell);
    }
}

/// Keeps up to [`MAX_PREVIEW_JOBS`] thumbnail renders in flight, visible
/// rows first (the pending queue is ordered that way by `load_window`).
fn dispatch_thumbnails(app: &mut App) {
    while app.preview_jobs.len() < MAX_PREVIEW_JOBS {
        let Some(index) = app.pending.pop_front() else {
            return;
        };
        let Some(asset) = app.items.get(index).map(|item| item.asset_id) else {
            continue; // the loaded window moved since this row was queued
        };
        let job = app.library.preview_async(asset, PreviewKind::Thumbnail);
        app.preview_jobs.insert(job);
    }
}

/// Fills the side panel when a cell is clicked or reached with the arrows.
fn wire_select(app: &Rc<RefCell<App>>, window: &StudioWindow) {
    let app = Rc::clone(app);
    let handle = window.as_weak();
    window.on_select(move |index| {
        let Some(window) = handle.upgrade() else {
            return;
        };
        show_details(&mut app.borrow_mut(), &window, index);
    });
}

/// Applies a classement key (`0`–`9`, `p`, `x`, `u`) to the selection.
fn wire_classify(app: &Rc<RefCell<App>>, window: &StudioWindow) {
    let app = Rc::clone(app);
    let handle = window.as_weak();
    window.on_classify(move |key| {
        let Some(window) = handle.upgrade() else {
            return;
        };
        let mut app = app.borrow_mut();
        let Some((version, label, pick)) = item_at(&app, window.get_selected())
            .map(|item| (item.version_id, item.color_label, item.pick))
        else {
            return;
        };
        let Some(action) = classify::from_key(key.as_str(), label, pick) else {
            return;
        };
        let applied = match action {
            Action::Rate(rating) => app.library.set_rating(&[version], rating),
            Action::Label(label) => app.library.set_color_label(&[version], label),
            Action::Flag(pick) => app.library.set_pick(&[version], pick),
        };
        if let Err(error) = applied
            .map_err(|e| e.to_string())
            .and_then(|()| reload(&mut app, &window))
        {
            report_error(&window, &error);
        }
    });
}

/// Connects the filter bar: stars, label dots, pick chips, sort cycling.
fn wire_filters(app: &Rc<RefCell<App>>, window: &StudioWindow) {
    let on_error = |window: &StudioWindow, result: Result<(), String>| {
        if let Err(error) = result {
            report_error(window, &error);
        }
    };

    {
        let app = Rc::clone(app);
        let handle = window.as_weak();
        window.on_rating_filter(move |stars| {
            let Some(window) = handle.upgrade() else {
                return;
            };
            let mut app = app.borrow_mut();
            app.query.rating_at_least =
                classify::toggle_rating_filter(app.query.rating_at_least, stars as u8);
            window.set_filter_rating(app.query.rating_at_least.map_or(0, i32::from));
            on_error(&window, reload(&mut app, &window));
        });
    }
    {
        let app = Rc::clone(app);
        let handle = window.as_weak();
        window.on_label_filter(move |value| {
            let Some(window) = handle.upgrade() else {
                return;
            };
            let Some(clicked) = ColorLabel::from_i64(i64::from(value)) else {
                return;
            };
            let mut app = app.borrow_mut();
            app.query.color_label = classify::toggle_label_filter(app.query.color_label, clicked);
            window.set_filter_label(app.query.color_label.map_or(-1, |l| l.as_i64() as i32));
            on_error(&window, reload(&mut app, &window));
        });
    }
    {
        let app = Rc::clone(app);
        let handle = window.as_weak();
        window.on_pick_filter(move |value| {
            let Some(window) = handle.upgrade() else {
                return;
            };
            let Some(clicked) = PickState::from_i64(i64::from(value)) else {
                return;
            };
            let mut app = app.borrow_mut();
            app.query.pick = classify::toggle_pick_filter(app.query.pick, clicked);
            window.set_filter_pick(app.query.pick.map_or(-1, |p| p.as_i64() as i32));
            on_error(&window, reload(&mut app, &window));
        });
    }
    {
        let app = Rc::clone(app);
        let handle = window.as_weak();
        window.on_search(move |text| {
            let Some(window) = handle.upgrade() else {
                return;
            };
            let mut app = app.borrow_mut();
            let text = text.trim();
            app.query.text = (!text.is_empty()).then(|| text.to_owned());
            on_error(&window, reload(&mut app, &window));
        });
    }
    {
        let app = Rc::clone(app);
        let handle = window.as_weak();
        window.on_cycle_sort(move || {
            let Some(window) = handle.upgrade() else {
                return;
            };
            let mut app = app.borrow_mut();
            let next = SORTS
                .iter()
                .position(|(sort, _)| *sort == app.query.sort)
                .map_or(0, |i| (i + 1) % SORTS.len());
            app.query.sort = SORTS[next].0;
            window.set_sort_label(SharedString::from(SORTS[next].1));
            on_error(&window, reload(&mut app, &window));
        });
    }
}

/// Connects the develop view: entering, sliders, undo / redo, leaving.
fn wire_develop(app: &Rc<RefCell<App>>, window: &StudioWindow) {
    {
        let app = Rc::clone(app);
        let handle = window.as_weak();
        window.on_enter_develop(move || {
            let Some(window) = handle.upgrade() else {
                return;
            };
            let mut app = app.borrow_mut();
            let Some((asset, version, filename)) = item_at(&app, window.get_selected())
                .map(|item| (item.asset_id, item.version_id, item.filename.clone()))
            else {
                return;
            };
            app.develop = Some((asset, version));
            match refresh_develop(&mut app, &window) {
                Ok(()) => {
                    window.set_develop_filename(SharedString::from(filename.as_str()));
                    window.set_develop_mode(true);
                }
                Err(error) => {
                    app.develop = None;
                    report_error(&window, &error);
                }
            }
        });
    }
    {
        let app = Rc::clone(app);
        let handle = window.as_weak();
        window.on_exit_develop(move || {
            let Some(window) = handle.upgrade() else {
                return;
            };
            let mut app = app.borrow_mut();
            app.develop = None;
            window.set_develop_mode(false);
            // Edits invalidated the thumbnails: rebuild the grid.
            if let Err(error) = reload(&mut app, &window) {
                report_error(&window, &error);
            }
        });
    }
    {
        let app = Rc::clone(app);
        let handle = window.as_weak();
        window.on_develop_edit(move |slider, value| {
            let Some(window) = handle.upgrade() else {
                return;
            };
            let mut app = app.borrow_mut();
            let Some((_, version)) = app.develop else {
                return;
            };
            let committed = (|| {
                let mut session = app.library.edit(version)?;
                let Some((param, value)) =
                    develop::action(slider.as_str(), f64::from(value), session.settings())
                else {
                    return Ok(());
                };
                session.set(param, value)?;
                session.commit().map(|_| ())
            })();
            if let Err(error) = committed
                .map_err(|e| e.to_string())
                .and_then(|()| refresh_develop(&mut app, &window))
            {
                report_error(&window, &error);
            }
        });
    }
    {
        let app = Rc::clone(app);
        let handle = window.as_weak();
        window.on_develop_crop_drag(move |px, py, rx, ry, vw, vh, iw, ih| {
            let Some(window) = handle.upgrade() else {
                return;
            };
            let mut app = app.borrow_mut();
            let Some((_, version)) = app.develop else {
                return;
            };
            let committed = (|| {
                let mut session = app.library.edit(version)?;
                let Some((param, value)) = develop::drag_crop(
                    (f64::from(px), f64::from(py)),
                    (f64::from(rx), f64::from(ry)),
                    (f64::from(vw), f64::from(vh)),
                    (f64::from(iw), f64::from(ih)),
                    &session.settings().crop,
                ) else {
                    return Ok(());
                };
                session.set(param, value)?;
                session.commit().map(|_| ())
            })();
            if let Err(error) = committed
                .map_err(|e| e.to_string())
                .and_then(|()| refresh_develop(&mut app, &window))
            {
                report_error(&window, &error);
            }
        });
    }
    {
        let app = Rc::clone(app);
        let handle = window.as_weak();
        window.on_develop_undo(move || {
            if let Some(window) = handle.upgrade() {
                history_step(&mut app.borrow_mut(), &window, true);
            }
        });
    }
    {
        let app = Rc::clone(app);
        let handle = window.as_weak();
        window.on_develop_redo(move || {
            if let Some(window) = handle.upgrade() {
                history_step(&mut app.borrow_mut(), &window, false);
            }
        });
    }
    {
        let app = Rc::clone(app);
        let handle = window.as_weak();
        window.on_develop_reprocess(move || {
            if let Some(window) = handle.upgrade() {
                reprocess_current(&mut app.borrow_mut(), &window);
            }
        });
    }
    {
        let app = Rc::clone(app);
        let handle = window.as_weak();
        window.on_reprocess_library(move || {
            if let Some(window) = handle.upgrade() {
                reprocess_library(&mut app.borrow_mut(), &window);
            }
        });
    }
    {
        let app = Rc::clone(app);
        let handle = window.as_weak();
        window.on_reprocess_selected(move || {
            if let Some(window) = handle.upgrade() {
                reprocess_selected(&mut app.borrow_mut(), &window);
            }
        });
    }
}

/// Migrates every version in the library to the current process version
/// (`docs/engine-api.md` §10.4), regardless of the active grid filter.
/// Reprocessing only rewrites `settings_json` — no pixels render during the
/// call — so this runs synchronously rather than as a tracked job, the same
/// way classement writes do.
fn reprocess_library(app: &mut App, window: &StudioWindow) {
    let query = GridQuery::default();
    let outcome = (|| {
        let count = app.library.catalog().count(&query)?;
        let all = GridQuery {
            range: 0..u32::try_from(count).unwrap_or(u32::MAX),
            ..query
        };
        let versions: Vec<VersionId> = app
            .library
            .catalog()
            .grid(&all)?
            .into_iter()
            .map(|item| item.version_id)
            .collect();
        app.library.reprocess(&versions, |_, _| {})
    })();
    match outcome {
        Ok(report) => {
            window.set_status_line(Tr::get(window).invoke_reprocessed(
                i32::try_from(report.reprocessed.len()).unwrap_or(i32::MAX),
                i32::try_from(report.already_current.len()).unwrap_or(i32::MAX),
                i32::try_from(report.failed.len()).unwrap_or(i32::MAX),
            ));
        }
        Err(error) => report_error(window, &error.to_string()),
    }
}

/// Grid context menu ▸ Reprocess (ADR 0021): the same `Library::reprocess`
/// call as `reprocess_library`/Shift+R, bounded to the single photo the
/// context menu was opened on rather than the whole catalog.
fn reprocess_selected(app: &mut App, window: &StudioWindow) {
    let Some(version) = item_at(app, window.get_selected()).map(|item| item.version_id) else {
        return;
    };
    match app.library.reprocess(&[version], |_, _| {}) {
        Ok(report) => {
            window.set_status_line(Tr::get(window).invoke_reprocessed(
                i32::try_from(report.reprocessed.len()).unwrap_or(i32::MAX),
                i32::try_from(report.already_current.len()).unwrap_or(i32::MAX),
                i32::try_from(report.failed.len()).unwrap_or(i32::MAX),
            ));
        }
        Err(error) => report_error(window, &error.to_string()),
    }
}

/// Connects the import and export dialogs.
fn wire_dialogs(app: &Rc<RefCell<App>>, window: &StudioWindow) {
    // File ▸ Quit (ADR 0020): stops the event loop, the same outcome as
    // closing the window from the OS chrome.
    window.on_quit(move || {
        let _ = slint::quit_event_loop();
    });
    {
        let app = Rc::clone(app);
        let handle = window.as_weak();
        window.on_run_import(move |source, copy, recursive| {
            let Some(window) = handle.upgrade() else {
                return;
            };
            let mut app = app.borrow_mut();
            if source.is_empty() {
                window.set_dialog_result(Tr::get(&window).invoke_enter_source_folder());
                return;
            }
            let options = ImportOptions {
                copy_files: copy,
                recursive,
            };
            let job = app
                .library
                .import_async(Path::new(source.as_str()), &options);
            app.import_job = Some(job);
            window.set_dialog_result(Tr::get(&window).invoke_importing_ellipsis());
        });
    }
    {
        let app = Rc::clone(app);
        let handle = window.as_weak();
        window.on_open_export(move || {
            let Some(window) = handle.upgrade() else {
                return;
            };
            let mut app = app.borrow_mut();
            let presets = match app.library.export_presets() {
                Ok(presets) => presets,
                Err(error) => {
                    report_error(&window, &error.to_string());
                    return;
                }
            };
            let names: Vec<SharedString> = presets
                .iter()
                .map(|preset| SharedString::from(preset.name.as_str()))
                .collect();
            app.presets = presets;
            window.set_export_presets(ModelRc::from(Rc::new(VecModel::from(names))));
            window.set_export_preset(-1);
            window.set_export_format(0);
            window.set_export_quality_text(SharedString::from("90"));
            window.set_export_max_edge_text(SharedString::default());
            window.set_export_preset_name(SharedString::default());
            window.set_dialog_result(SharedString::default());
            window.set_dialog(SharedString::from("export"));
        });
    }
    {
        let app = Rc::clone(app);
        let handle = window.as_weak();
        window.on_run_export(move |preset, destination, format, quality, max_edge| {
            let Some(window) = handle.upgrade() else {
                return;
            };
            let mut app = app.borrow_mut();
            let Some(version) = item_at(&app, window.get_selected()).map(|item| item.version_id)
            else {
                window.set_dialog_result(Tr::get(&window).invoke_select_photo_first());
                return;
            };
            if destination.is_empty() {
                window.set_dialog_result(Tr::get(&window).invoke_enter_destination_folder());
                return;
            }
            let destination = PathBuf::from(destination.as_str());
            let stored = usize::try_from(preset)
                .ok()
                .and_then(|i| app.presets.get(i))
                .map(|preset| preset.preset);
            let job = match stored {
                Some(id) => app
                    .library
                    .export_with_preset_async(vec![version], id, destination),
                None => {
                    let settings = match export_settings(format, &quality, &max_edge) {
                        Ok(settings) => settings,
                        Err(message) => {
                            window.set_dialog_result(SharedString::from(message));
                            return;
                        }
                    };
                    app.library
                        .export_async(vec![version], settings, destination)
                }
            };
            app.export_job = Some(job);
            window.set_dialog_result(Tr::get(&window).invoke_exporting_ellipsis());
        });
    }
    {
        let app = Rc::clone(app);
        let handle = window.as_weak();
        window.on_run_save_export_preset(move |name, format, quality, max_edge| {
            let Some(window) = handle.upgrade() else {
                return;
            };
            if name.trim().is_empty() {
                window.set_dialog_result(Tr::get(&window).invoke_enter_a_name());
                return;
            }
            let (name, settings) = match export_preset_request(&name, format, &quality, &max_edge) {
                Ok(request) => request,
                Err(message) => {
                    window.set_dialog_result(SharedString::from(message));
                    return;
                }
            };
            let mut app = app.borrow_mut();
            let saved = app
                .library
                .create_export_preset(&name, &settings)
                .map_err(|e| e.to_string())
                .and_then(|_| refresh_export_presets(&mut app, &window));
            match saved {
                Ok(()) => {
                    window.set_export_preset_name(SharedString::default());
                    window.set_dialog_result(Tr::get(&window).invoke_preset_saved());
                }
                Err(error) => {
                    window.set_dialog_result(
                        Tr::get(&window).invoke_save_failed(SharedString::from(error)),
                    );
                }
            }
        });
    }
}

/// Reloads the export dialog's preset picker from the catalog (mirrors
/// `refresh_presets` for develop presets).
fn refresh_export_presets(app: &mut App, window: &StudioWindow) -> Result<(), String> {
    let presets = app.library.export_presets().map_err(|e| e.to_string())?;
    let names: Vec<SharedString> = presets
        .iter()
        .map(|preset| SharedString::from(preset.name.as_str()))
        .collect();
    app.presets = presets;
    window.set_export_presets(ModelRc::from(Rc::new(VecModel::from(names))));
    Ok(())
}

/// Builds an ad-hoc `ExportSettings` from the export dialog's custom fields
/// (the `Custom` chip, as opposed to a stored preset).
fn export_settings(format: i32, quality: &str, max_edge: &str) -> Result<ExportSettings, String> {
    let format = match format {
        0 => ExportFormat::Jpeg,
        1 => ExportFormat::Png,
        2 => ExportFormat::Tiff,
        3 => ExportFormat::Webp,
        4 => ExportFormat::Avif,
        other => return Err(format!("unknown export format index {other}")),
    };
    let quality = quality
        .parse()
        .map_err(|_| format!("bad quality {quality:?}"))?;
    let max_edge = if max_edge.trim().is_empty() {
        None
    } else {
        Some(
            max_edge
                .parse()
                .map_err(|_| format!("bad max edge {max_edge:?}"))?,
        )
    };
    Ok(ExportSettings {
        format,
        quality,
        max_edge,
    })
}

/// Builds a `(name, ExportSettings)` request for saving the export dialog's
/// custom fields as a reusable preset — trims and validates the name, then
/// reuses `export_settings` so the recipe validation isn't duplicated.
fn export_preset_request(
    name: &str,
    format: i32,
    quality: &str,
    max_edge: &str,
) -> Result<(String, ExportSettings), String> {
    let name = name.trim();
    if name.is_empty() {
        return Err("name is empty".to_owned());
    }
    let settings = export_settings(format, quality, max_edge)?;
    Ok((name.to_owned(), settings))
}

/// Connects the collections sidebar and its creation dialog.
fn wire_collections(app: &Rc<RefCell<App>>, window: &StudioWindow) {
    {
        let app = Rc::clone(app);
        let handle = window.as_weak();
        window.on_select_collection(move |index| {
            let Some(window) = handle.upgrade() else {
                return;
            };
            let mut app = app.borrow_mut();
            let picked = usize::try_from(index)
                .ok()
                .and_then(|i| app.collections.get(i))
                .copied();
            window.set_active_collection(if picked.is_some() { index } else { -1 });
            app.query.collection = picked;
            if let Err(error) = reload(&mut app, &window) {
                report_error(&window, &error);
            }
        });
    }
    {
        let app = Rc::clone(app);
        let handle = window.as_weak();
        window.on_run_new_collection(move |name| {
            let Some(window) = handle.upgrade() else {
                return;
            };
            let name = name.trim();
            if name.is_empty() {
                window.set_dialog_result(Tr::get(&window).invoke_enter_a_name());
                return;
            }
            let mut app = app.borrow_mut();
            let created = app
                .library
                .create_collection(None, name)
                .map_err(|e| e.to_string())
                .and_then(|_| refresh_collections(&mut app, &window));
            match created {
                Ok(()) => window.set_dialog(SharedString::default()),
                Err(error) => window.set_dialog_result(
                    Tr::get(&window).invoke_creation_failed(SharedString::from(error)),
                ),
            }
        });
    }
    {
        let app = Rc::clone(app);
        let handle = window.as_weak();
        window.on_add_to_collection(move || {
            if let Some(window) = handle.upgrade() {
                collection_membership(&mut app.borrow_mut(), &window, true);
            }
        });
    }
    {
        let app = Rc::clone(app);
        let handle = window.as_weak();
        window.on_remove_from_collection(move || {
            if let Some(window) = handle.upgrade() {
                collection_membership(&mut app.borrow_mut(), &window, false);
            }
        });
    }
}

/// Connects the keyword panel: tagging by path, untagging by row.
fn wire_keywords(app: &Rc<RefCell<App>>, window: &StudioWindow) {
    {
        let app = Rc::clone(app);
        let handle = window.as_weak();
        window.on_add_keyword(move |path| {
            let Some(window) = handle.upgrade() else {
                return;
            };
            let mut app = app.borrow_mut();
            let path = path.trim().to_owned();
            if path.is_empty() {
                return;
            }
            let Some(asset) = item_at(&app, window.get_selected()).map(|item| item.asset_id) else {
                return;
            };
            let tagged = ensure_keyword_path(&mut app, &path).and_then(|keyword| {
                app.library
                    .add_keyword(&[asset], keyword)
                    .map_err(|e| e.to_string())
            });
            // Reload rather than refresh the panel alone: a text search may
            // now match (or no longer match) the tagged photo.
            if let Err(error) = tagged.and_then(|()| reload(&mut app, &window)) {
                report_error(&window, &error);
            }
        });
    }
    {
        let app = Rc::clone(app);
        let handle = window.as_weak();
        window.on_remove_keyword(move |index| {
            let Some(window) = handle.upgrade() else {
                return;
            };
            let mut app = app.borrow_mut();
            let Some(asset) = item_at(&app, window.get_selected()).map(|item| item.asset_id) else {
                return;
            };
            let Some(keyword) = usize::try_from(index)
                .ok()
                .and_then(|i| app.keywords.get(i))
                .copied()
            else {
                return;
            };
            if app.keyword_filter == Some(keyword) {
                app.keyword_filter = None;
                app.query.keywords.clear();
            }
            let untagged = app
                .library
                .remove_keyword(&[asset], keyword)
                .map_err(|e| e.to_string());
            if let Err(error) = untagged.and_then(|()| reload(&mut app, &window)) {
                report_error(&window, &error);
            }
        });
    }
    {
        let app = Rc::clone(app);
        let handle = window.as_weak();
        window.on_keyword_filter(move |index| {
            let Some(window) = handle.upgrade() else {
                return;
            };
            let mut app = app.borrow_mut();
            let Some(keyword) = usize::try_from(index)
                .ok()
                .and_then(|i| app.keywords.get(i))
                .copied()
            else {
                return;
            };
            app.keyword_filter = if app.keyword_filter == Some(keyword) {
                None
            } else {
                Some(keyword)
            };
            app.query.keywords = app.keyword_filter.into_iter().collect();
            window.set_filter_keyword_label(
                app.keyword_filter
                    .and_then(|k| app.keywords.iter().position(|&x| x == k))
                    .and_then(|i| window.get_detail_keywords().row_data(i))
                    .unwrap_or_default(),
            );
            if let Err(error) = reload(&mut app, &window) {
                report_error(&window, &error);
            }
        });
    }
    {
        let app = Rc::clone(app);
        let handle = window.as_weak();
        window.on_clear_keyword_filter(move || {
            let Some(window) = handle.upgrade() else {
                return;
            };
            let mut app = app.borrow_mut();
            app.keyword_filter = None;
            app.query.keywords.clear();
            window.set_filter_keyword_label(SharedString::default());
            if let Err(error) = reload(&mut app, &window) {
                report_error(&window, &error);
            }
        });
    }
}

/// Connects the develop presets panel: applying, deleting, and the
/// save-as-preset dialog (`docs/presets.md` §6).
fn wire_presets(app: &Rc<RefCell<App>>, window: &StudioWindow) {
    {
        let handle = window.as_weak();
        window.on_open_preset_dialog(move || {
            let Some(window) = handle.upgrade() else {
                return;
            };
            window.set_dialog_result(SharedString::default());
            window.set_dialog(SharedString::from("preset"));
        });
    }
    {
        let app = Rc::clone(app);
        let handle = window.as_weak();
        window.on_run_save_preset(
            move |name, white_balance, tone, presence, lens_correction, detail, geometry| {
                let Some(window) = handle.upgrade() else {
                    return;
                };
                let name = name.trim();
                if name.is_empty() {
                    window.set_dialog_result(Tr::get(&window).invoke_enter_a_name());
                    return;
                }
                let mut app = app.borrow_mut();
                let Some((_, version)) = app.develop else {
                    window.set_dialog_result(Tr::get(&window).invoke_open_photo_in_develop_first());
                    return;
                };
                let flags = [
                    (white_balance, SettingsGroup::WhiteBalance),
                    (tone, SettingsGroup::Tone),
                    (presence, SettingsGroup::Presence),
                    (lens_correction, SettingsGroup::LensCorrection),
                    (detail, SettingsGroup::Detail),
                    (geometry, SettingsGroup::Geometry),
                ];
                let groups: Vec<SettingsGroup> = flags
                    .into_iter()
                    .filter_map(|(on, group)| on.then_some(group))
                    .collect();
                if groups.is_empty() {
                    window.set_dialog_result(Tr::get(&window).invoke_pick_at_least_one_group());
                    return;
                }
                let saved = app
                    .library
                    .create_preset(name, version, &groups)
                    .map_err(|e| e.to_string())
                    .and_then(|_| refresh_presets(&mut app, &window));
                match saved {
                    Ok(()) => window.set_dialog(SharedString::default()),
                    Err(error) => {
                        window.set_dialog_result(
                            Tr::get(&window).invoke_save_failed(SharedString::from(error)),
                        );
                    }
                }
            },
        );
    }
    {
        let app = Rc::clone(app);
        let handle = window.as_weak();
        window.on_apply_preset(move |index| {
            let Some(window) = handle.upgrade() else {
                return;
            };
            let mut app = app.borrow_mut();
            let Some((_, version)) = app.develop else {
                return;
            };
            let Some(preset) = usize::try_from(index)
                .ok()
                .and_then(|i| app.dev_presets.get(i))
                .map(|p| p.preset)
            else {
                return;
            };
            let applied = app
                .library
                .apply_preset(preset, &[version], |_, _| {})
                .map_err(|e| e.to_string());
            match applied {
                Ok(report) => {
                    if let Some(failed) = report.failed.first() {
                        report_error(&window, &failed.reason);
                    } else if let Err(error) = refresh_develop(&mut app, &window) {
                        report_error(&window, &error);
                    }
                }
                Err(error) => report_error(&window, &error),
            }
        });
    }
    {
        let app = Rc::clone(app);
        let handle = window.as_weak();
        window.on_delete_preset(move |index| {
            let Some(window) = handle.upgrade() else {
                return;
            };
            let mut app = app.borrow_mut();
            let Some(preset) = usize::try_from(index)
                .ok()
                .and_then(|i| app.dev_presets.get(i))
                .map(|p| p.preset)
            else {
                return;
            };
            let deleted = app
                .library
                .delete_preset(preset)
                .map_err(|e| e.to_string())
                .and_then(|()| refresh_presets(&mut app, &window));
            if let Err(error) = deleted {
                report_error(&window, &error);
            }
        });
    }
}

/// Reloads the develop sidebar's preset list from the catalog.
fn refresh_presets(app: &mut App, window: &StudioWindow) -> Result<(), String> {
    let presets = app.library.presets().map_err(|e| e.to_string())?;
    let names: Vec<SharedString> = presets
        .iter()
        .map(|preset| SharedString::from(preset.name.as_str()))
        .collect();
    app.dev_presets = presets;
    window.set_dev_presets(ModelRc::from(Rc::new(VecModel::from(names))));
    Ok(())
}

/// Finds or creates the keyword at a slash-separated path (`Nature/Birds`),
/// creating the missing levels, and returns the leaf keyword.
fn ensure_keyword_path(app: &mut App, path: &str) -> Result<KeywordId, String> {
    let tree = app.library.keyword_tree().map_err(|e| e.to_string())?;
    let (mut parent, missing) = resolve_keyword_path(&tree, path)?;
    for level in missing {
        parent = Some(
            app.library
                .create_keyword(parent, &level)
                .map_err(|e| e.to_string())?,
        );
    }
    parent.ok_or_else(|| "enter a keyword".to_owned())
}

/// Walks the keyword tree along a slash-separated path and returns the
/// deepest existing keyword plus the levels still to create beneath it.
fn resolve_keyword_path(
    tree: &[KeywordNode],
    path: &str,
) -> Result<(Option<KeywordId>, Vec<String>), String> {
    let mut parent = None;
    let mut siblings = tree;
    let mut missing = Vec::new();
    for level in path.split('/') {
        let level = level.trim();
        if level.is_empty() {
            return Err("keyword levels cannot be empty".to_owned());
        }
        if !missing.is_empty() {
            missing.push(level.to_owned());
            continue;
        }
        match siblings.iter().find(|node| node.name == level) {
            Some(node) => {
                parent = Some(node.keyword);
                siblings = &node.children;
            }
            None => missing.push(level.to_owned()),
        }
    }
    Ok((parent, missing))
}

/// The keywords of an asset as parallel `(ids, full paths)` panel rows.
fn keyword_rows(app: &App, asset: AssetId) -> Result<(Vec<KeywordId>, Vec<SharedString>), String> {
    let ids = app
        .library
        .catalog()
        .asset_keywords(asset)
        .map_err(|e| e.to_string())?;
    let tree = app.library.keyword_tree().map_err(|e| e.to_string())?;
    let mut paths = std::collections::HashMap::new();
    collect_keyword_paths(&tree, &mut paths);
    let names = ids
        .iter()
        .map(|id| SharedString::from(paths.get(id).map_or("?", String::as_str)))
        .collect();
    Ok((ids, names))
}

/// Flattens the keyword tree into an id → full path map.
fn collect_keyword_paths(
    nodes: &[KeywordNode],
    out: &mut std::collections::HashMap<KeywordId, String>,
) {
    for node in nodes {
        out.insert(node.keyword, node.path.clone());
        collect_keyword_paths(&node.children, out);
    }
}

/// Adds the selected photo's version to the active collection, or removes
/// it, then reloads the grid (membership may change what it shows).
fn collection_membership(app: &mut App, window: &StudioWindow, add: bool) {
    let Some(collection) = usize::try_from(window.get_active_collection())
        .ok()
        .and_then(|i| app.collections.get(i))
        .copied()
    else {
        report_error(window, &Tr::get(window).invoke_select_collection_first());
        return;
    };
    let Some(version) = item_at(app, window.get_selected()).map(|item| item.version_id) else {
        return;
    };
    let changed = if add {
        app.library.add_to_collection(collection, &[version])
    } else {
        app.library.remove_from_collection(collection, &[version])
    };
    if let Err(error) = changed
        .map_err(|e| e.to_string())
        .and_then(|()| reload(app, window))
    {
        report_error(window, &error);
    }
}

/// Reloads the sidebar from the catalog's collection tree.
fn refresh_collections(app: &mut App, window: &StudioWindow) -> Result<(), String> {
    let tree = app.library.collections().map_err(|e| e.to_string())?;
    let mut flat = Vec::new();
    flatten_collections(&tree, 0, &mut flat);
    app.collections = flat.iter().map(|(id, ..)| *id).collect();
    let rows: Vec<ui::CollectionRow> = flat
        .into_iter()
        .map(|(_, name, depth, smart)| ui::CollectionRow {
            name: SharedString::from(name),
            depth,
            smart,
        })
        .collect();
    window.set_collections(ModelRc::from(Rc::new(VecModel::from(rows))));
    Ok(())
}

/// Flattens the collection tree into `(id, name, depth, smart)` sidebar
/// rows, depth first, children under their parent.
fn flatten_collections(
    nodes: &[CollectionNode],
    depth: i32,
    out: &mut Vec<(CollectionId, String, i32, bool)>,
) {
    for node in nodes {
        out.push((
            node.collection,
            node.name.clone(),
            depth,
            node.collection_type == CollectionType::Smart,
        ));
        flatten_collections(&node.children, depth + 1, out);
    }
}

/// One line summing up an import batch for the dialog.
fn import_summary(imported: usize, skipped: &[SkippedFile]) -> String {
    match skipped {
        [] => format!("{imported} imported."),
        [first, ..] => format!(
            "{imported} imported, {} skipped ({}).",
            skipped.len(),
            first.reason
        ),
    }
}

/// One line summing up an export batch for the dialog.
fn export_summary(report: &ExportReport) -> String {
    match (report.exported.first(), report.failed.first()) {
        (Some(done), _) => format!("Exported to {}.", done.path.display()),
        (None, Some(failed)) => format!("Export failed: {}", failed.reason),
        (None, None) => "Nothing to export.".to_owned(),
    }
}

/// Moves the develop head one revision back or forward, then refreshes.
fn history_step(app: &mut App, window: &StudioWindow, undo: bool) {
    let Some((_, version)) = app.develop else {
        return;
    };
    let moved = (|| {
        let mut session = app.library.edit(version)?;
        if undo { session.undo() } else { session.redo() }
    })();
    if let Err(error) = moved
        .map_err(|e| e.to_string())
        .and_then(|_| refresh_develop(app, window))
    {
        report_error(window, &error);
    }
}

/// Migrates the open photo to the engine's current process version
/// (`docs/engine-api.md` §10.4) — a new revision with the same parameter
/// values, so a photo imported before a rendering feature existed (e.g.
/// lens correction) can pick it up without the user touching a slider. A
/// no-op, silently, when the head is already current.
fn reprocess_current(app: &mut App, window: &StudioWindow) {
    let Some((_, version)) = app.develop else {
        return;
    };
    let reprocessed = (|| {
        let mut session = app.library.edit(version)?;
        session.reprocess()
    })();
    if let Err(error) = reprocessed
        .map_err(|e| e.to_string())
        .and_then(|_| refresh_develop(app, window))
    {
        report_error(window, &error);
    }
}

/// Renders the develop preview at the head settings and mirrors those
/// settings into the sliders.
fn refresh_develop(app: &mut App, window: &StudioWindow) -> Result<(), String> {
    let Some((asset, version)) = app.develop else {
        return Ok(());
    };
    let settings = {
        let session = app.library.edit(version).map_err(|e| e.to_string())?;
        session.settings().clone()
    };
    window.set_dev(dev_model(&settings));
    let file = app
        .library
        .preview(asset, PreviewKind::Small)
        .map_err(|e| e.to_string())?;
    let image = slint::Image::load_from_path(&file.path)
        .map_err(|_| format!("cannot load preview {}", file.path.display()))?;
    window.set_develop_image(image);
    Ok(())
}

/// Mirrors pipeline settings into the develop slider model.
fn dev_model(settings: &Settings) -> ui::DevSettings {
    let wb = settings.white_balance.clone().unwrap_or_default();
    let crop = settings.crop.clone().unwrap_or(leyline_sdk::Crop {
        x: 0.0,
        y: 0.0,
        width: 1.0,
        height: 1.0,
    });
    ui::DevSettings {
        exposure: settings.exposure as f32,
        contrast: settings.contrast as f32,
        highlights: settings.highlights as f32,
        shadows: settings.shadows as f32,
        whites: settings.whites as f32,
        blacks: settings.blacks as f32,
        vibrance: settings.vibrance as f32,
        saturation: settings.saturation as f32,
        wb_temp: wb.temperature as f32,
        wb_tint: wb.tint as f32,
        rotation: settings.rotation as f32,
        crop_left: (crop.x * 100.0) as f32,
        crop_top: (crop.y * 100.0) as f32,
        crop_width: (crop.width * 100.0) as f32,
        crop_height: (crop.height * 100.0) as f32,
        nr_luminance: settings.noise_reduction.luminance as f32,
        nr_color: settings.noise_reduction.color as f32,
        sharpen_amount: settings.sharpening.amount as f32,
        sharpen_radius: settings.sharpening.radius as f32,
        lens_correction: settings.lens_correction.enabled,
    }
}

/// Surfaces a callback failure in the status line, where a GUI user can
/// see it; stderr keeps a copy for terminal logs.
fn report_error(window: &StudioWindow, message: &str) {
    eprintln!("error: {message}");
    window.set_status_line(Tr::get(window).invoke_error_prefix(SharedString::from(message)));
}

/// The window worth loading for a viewport: the visible cells plus the
/// overscan margin on each side, clamped to the grid.
fn desired_window(viewport: (usize, usize), total: u64) -> std::ops::Range<usize> {
    let (first, capacity) = viewport;
    let total = usize::try_from(total).unwrap_or(usize::MAX);
    let start = first.saturating_sub(OVERSCAN).min(total);
    let end = first
        .saturating_add(capacity)
        .saturating_add(OVERSCAN)
        .min(total);
    start..end.max(start)
}

/// True when the loaded window no longer serves the viewport: part of the
/// visible range is missing, or an edge with more rows beyond it is closer
/// than half the overscan margin.
fn window_is_stale(viewport: (usize, usize), loaded: &std::ops::Range<usize>, total: u64) -> bool {
    let (first, capacity) = viewport;
    let total = usize::try_from(total).unwrap_or(usize::MAX);
    let visible_end = first.saturating_add(capacity).min(total);
    first < loaded.start
        || visible_end > loaded.end
        || (loaded.start > 0 && first < loaded.start + OVERSCAN / 2)
        || (loaded.end < total && visible_end + OVERSCAN / 2 > loaded.end)
}

/// The grid item shown at a whole-grid index, when it is loaded.
fn item_at(app: &App, index: i32) -> Option<&GridItem> {
    usize::try_from(index)
        .ok()?
        .checked_sub(app.window_start)
        .and_then(|i| app.items.get(i))
}

/// Fetches the window of rows serving the current viewport and rebuilds
/// the cell model from it (virtual scrolling: the rest of the grid only
/// exists as the scrollbar's extent).
fn load_window(app: &mut App, window: &StudioWindow) -> Result<(), String> {
    let range = desired_window(app.viewport, app.total);
    app.query.range = u32::try_from(range.start).unwrap_or(u32::MAX)
        ..u32::try_from(range.end).unwrap_or(u32::MAX);
    let items = app
        .library
        .catalog()
        .grid(&app.query)
        .map_err(|e| e.to_string())?;

    // Only thumbnails already cached are loaded here, so the window appears
    // instantly; the rest are queued and rendered by the thumbnail timer,
    // visible cells before the overscan rows above them.
    let first_visible = app.viewport.0.saturating_sub(range.start);
    let mut cells = Vec::with_capacity(items.len());
    let mut missing = Vec::new();
    for (index, item) in items.iter().enumerate() {
        let thumbnail = app
            .library
            .cached_preview(item.asset_id, PreviewKind::Thumbnail)
            .ok()
            .flatten()
            .and_then(|file| slint::Image::load_from_path(&file.path).ok());
        if thumbnail.is_none() {
            missing.push(index);
        }
        cells.push(Cell {
            thumbnail: thumbnail.unwrap_or_default(),
            filename: SharedString::from(item.filename.as_str()),
            stars: SharedString::from(format::stars(item.rating)),
            label: label_color(item.color_label),
            has_label: item.color_label.is_some(),
        });
    }
    let (visible, above): (VecDeque<usize>, VecDeque<usize>) = missing
        .into_iter()
        .partition(|&index| index >= first_visible);
    app.items = items;
    app.window_start = range.start;
    app.pending = visible.into_iter().chain(above).collect();
    app.cells = Rc::new(VecModel::from(cells));

    window.set_cells(ModelRc::from(Rc::clone(&app.cells)));
    window.set_window_start(i32::try_from(range.start).unwrap_or(i32::MAX));

    // The selection may have just scrolled into the loaded window (arrow
    // navigation past the edge): fill the side panel now that its row exists.
    let selected = window.get_selected();
    if item_at(app, selected).is_some() {
        show_details(app, window, selected);
    }
    Ok(())
}

/// Re-runs the grid query — count plus the visible window — and rebuilds
/// the cell model, keeping the current selection when the same version is
/// still in the loaded window.
fn reload(app: &mut App, window: &StudioWindow) -> Result<(), String> {
    let keep: Option<VersionId> = item_at(app, window.get_selected()).map(|item| item.version_id);

    app.total = app
        .library
        .catalog()
        .count(&app.query)
        .map_err(|e| e.to_string())?;
    let total = i32::try_from(app.total).unwrap_or(i32::MAX);
    window.set_total_cells(total);
    window.set_status_line(Tr::get(window).invoke_photo_count(total));
    load_window(app, window)?;

    let selected = keep
        .and_then(|version| app.items.iter().position(|item| item.version_id == version))
        .and_then(|i| i32::try_from(i + app.window_start).ok())
        .unwrap_or(-1);
    window.set_selected(selected);
    if selected >= 0 {
        show_details(app, window, selected);
    }
    Ok(())
}

/// Reads and formats everything the side panel shows for one grid row.
fn show_details(app: &mut App, window: &StudioWindow, index: i32) {
    let Some(asset) = item_at(app, index).map(|item| item.asset_id) else {
        return;
    };
    let details = match app.library.catalog().asset_details(asset) {
        Ok(details) => details,
        Err(error) => {
            eprintln!("error: {error}");
            return;
        }
    };
    match keyword_rows(app, asset) {
        Ok((ids, paths)) => {
            app.keywords = ids;
            window.set_detail_keywords(ModelRc::from(Rc::new(VecModel::from(paths))));
        }
        Err(error) => eprintln!("error: {error}"),
    }
    let meta = details.metadata.as_ref();
    window.set_detail_filename(SharedString::from(details.filename.as_str()));
    window.set_detail_path(SharedString::from(details.relative_path.as_str()));
    window.set_detail_capture(SharedString::from(
        details
            .capture_date
            .map_or_else(|| "—".to_owned(), format::capture_date),
    ));
    window.set_detail_dimensions(SharedString::from(format::dimensions(
        details.width,
        details.height,
    )));
    window.set_detail_file_size(SharedString::from(format::file_size(details.file_size)));
    window.set_detail_camera(SharedString::from(
        meta.and_then(|m| m.camera.as_ref()).map_or_else(
            || "—".to_owned(),
            |c| format!("{} {}", c.manufacturer, c.model),
        ),
    ));
    window.set_detail_lens(SharedString::from(
        meta.and_then(|m| m.lens.as_ref()).map_or_else(
            || "—".to_owned(),
            |l| format!("{} {}", l.manufacturer, l.model),
        ),
    ));
    window.set_detail_exposure(SharedString::from(
        meta.map_or_else(String::new, format::exposure_line),
    ));
}

/// The label shown on the sort button for a sort order.
fn sort_label(sort: Sort) -> &'static str {
    SORTS
        .iter()
        .find(|(candidate, _)| *candidate == sort)
        .map_or(SORTS[0].1, |(_, label)| label)
}

/// The dot color of a catalog color label.
fn label_color(label: Option<ColorLabel>) -> slint::Color {
    match label {
        Some(ColorLabel::Red) => slint::Color::from_rgb_u8(0xE0, 0x4F, 0x4F),
        Some(ColorLabel::Yellow) => slint::Color::from_rgb_u8(0xE0, 0xC0, 0x4F),
        Some(ColorLabel::Green) => slint::Color::from_rgb_u8(0x6F, 0xBF, 0x6F),
        Some(ColorLabel::Blue) => slint::Color::from_rgb_u8(0x5F, 0x8F, 0xDF),
        Some(ColorLabel::Purple) => slint::Color::from_rgb_u8(0xA0, 0x6F, 0xDF),
        None => slint::Color::default(),
    }
}

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use leyline_sdk::{ExportedVersion, FailedExport};

    use super::*;

    #[test]
    fn import_summaries_count_and_explain() {
        assert_eq!(import_summary(3, &[]), "3 imported.");
        let skipped = vec![
            SkippedFile {
                path: PathBuf::from("/photos/a.xmp"),
                reason: "unsupported file type".to_owned(),
            },
            SkippedFile {
                path: PathBuf::from("/photos/b.xmp"),
                reason: "unsupported file type".to_owned(),
            },
        ];
        assert_eq!(
            import_summary(1, &skipped),
            "1 imported, 2 skipped (unsupported file type)."
        );
    }

    #[test]
    fn export_settings_parses_every_format_and_blank_max_edge() {
        for (index, format) in [
            ExportFormat::Jpeg,
            ExportFormat::Png,
            ExportFormat::Tiff,
            ExportFormat::Webp,
            ExportFormat::Avif,
        ]
        .into_iter()
        .enumerate()
        {
            let settings = export_settings(index as i32, "80", "").unwrap();
            assert_eq!(
                settings,
                ExportSettings {
                    format,
                    quality: 80,
                    max_edge: None,
                }
            );
        }
    }

    #[test]
    fn export_settings_parses_a_max_edge() {
        let settings = export_settings(0, "90", "2048").unwrap();
        assert_eq!(settings.max_edge, Some(2048));
    }

    #[test]
    fn export_settings_rejects_bad_input() {
        assert!(export_settings(5, "90", "").is_err());
        assert!(export_settings(0, "not a number", "").is_err());
        assert!(export_settings(0, "90", "not a number").is_err());
    }

    #[test]
    fn export_preset_request_trims_the_name_and_reuses_export_settings() {
        let (name, settings) = export_preset_request("  Web  ", 0, "80", "2048").unwrap();
        assert_eq!(name, "Web");
        assert_eq!(
            settings,
            ExportSettings {
                format: ExportFormat::Jpeg,
                quality: 80,
                max_edge: Some(2048),
            }
        );
    }

    #[test]
    fn export_preset_request_rejects_a_blank_or_whitespace_only_name() {
        assert!(export_preset_request("", 0, "80", "").is_err());
        assert!(export_preset_request("   ", 0, "80", "").is_err());
    }

    #[test]
    fn export_preset_request_still_validates_the_recipe() {
        assert!(export_preset_request("Web", 0, "not a number", "").is_err());
        assert!(export_preset_request("Web", 5, "80", "").is_err());
    }

    #[test]
    fn flattening_keeps_children_under_their_parent() {
        let node = |id: i64, name: &str, children: Vec<CollectionNode>| CollectionNode {
            collection: CollectionId::new(id),
            name: name.to_owned(),
            description: None,
            collection_type: CollectionType::Manual,
            children,
        };
        let tree = vec![
            node(1, "Travel", vec![node(2, "Iceland", vec![])]),
            node(3, "Portfolio", vec![]),
        ];
        let mut flat = Vec::new();
        flatten_collections(&tree, 0, &mut flat);
        let shape: Vec<(i64, &str, i32)> = flat
            .iter()
            .map(|(id, name, depth, _)| (id.get(), name.as_str(), *depth))
            .collect();
        assert_eq!(
            shape,
            vec![(1, "Travel", 0), (2, "Iceland", 1), (3, "Portfolio", 0)]
        );
    }

    #[test]
    fn desired_window_pads_the_viewport_and_clamps_to_the_grid() {
        assert_eq!(desired_window((0, 30), 10_000), 0..30 + OVERSCAN);
        assert_eq!(
            desired_window((500, 30), 10_000),
            500 - OVERSCAN..530 + OVERSCAN
        );
        assert_eq!(desired_window((980, 30), 1_000), 980 - OVERSCAN..1_000);
        assert_eq!(desired_window((0, 30), 10), 0..10);
    }

    #[test]
    fn window_goes_stale_near_an_edge_with_rows_beyond_it() {
        let loaded = 452..578; // desired_window((500, 30), 10_000)
        assert!(!window_is_stale((500, 30), &loaded, 10_000));
        // Drifting towards an edge crosses the half-overscan threshold.
        assert!(window_is_stale((460, 30), &loaded, 10_000));
        assert!(window_is_stale((530, 30), &loaded, 10_000));
        // A jump lands entirely outside the loaded window.
        assert!(window_is_stale((2_000, 30), &loaded, 10_000));
        // At the ends of the grid the margin has nothing left to fetch.
        assert!(!window_is_stale((0, 30), &(0..126), 10_000));
        assert!(!window_is_stale((970, 30), &(922..1_000), 1_000));
    }

    #[test]
    fn keyword_paths_resolve_existing_levels_and_list_missing_ones() {
        let node = |id: i64, name: &str, path: &str, children: Vec<KeywordNode>| KeywordNode {
            keyword: KeywordId::new(id),
            name: name.to_owned(),
            path: path.to_owned(),
            children,
        };
        let tree = vec![node(
            1,
            "Nature",
            "Nature",
            vec![node(2, "Birds", "Nature/Birds", vec![])],
        )];

        // A fully existing path resolves to its leaf, nothing to create.
        let (parent, missing) = resolve_keyword_path(&tree, "Nature/Birds").unwrap();
        assert_eq!((parent, missing), (Some(KeywordId::new(2)), vec![]));

        // A partly existing path stops at the deepest known level; spaces
        // around levels are trimmed.
        let (parent, missing) = resolve_keyword_path(&tree, "Nature / Birds / Heron").unwrap();
        assert_eq!(parent, Some(KeywordId::new(2)));
        assert_eq!(missing, vec!["Heron".to_owned()]);

        // A brand-new root creates every level.
        let (parent, missing) = resolve_keyword_path(&tree, "Travel/Iceland").unwrap();
        assert_eq!(parent, None);
        assert_eq!(missing, vec!["Travel".to_owned(), "Iceland".to_owned()]);

        // Empty levels are refused.
        assert!(resolve_keyword_path(&tree, "Nature//Heron").is_err());
        assert!(resolve_keyword_path(&tree, "/").is_err());

        // The id → path map covers nested nodes.
        let mut paths = std::collections::HashMap::new();
        collect_keyword_paths(&tree, &mut paths);
        assert_eq!(paths[&KeywordId::new(2)], "Nature/Birds");
    }

    #[test]
    fn export_summaries_show_the_file_or_the_failure() {
        let mut report = ExportReport::default();
        assert_eq!(export_summary(&report), "Nothing to export.");
        report.failed.push(FailedExport {
            version: VersionId::new(7),
            reason: "no such version".to_owned(),
        });
        assert_eq!(export_summary(&report), "Export failed: no such version");
        report.exported.push(ExportedVersion {
            version: VersionId::new(7),
            path: PathBuf::from("/out/photo.jpg"),
        });
        assert_eq!(export_summary(&report), "Exported to /out/photo.jpg.");
    }
}
