//! Roots: the folders a library may reference photos inside
//! (`docs/catalog.md` §2.3, [ADR 0085](../../../docs/adr/0085-named-roots.md)).
//!
//! A root is an **identity, not a location**. It is a UUID and a name, and
//! nothing here records where it sits: that is what lets a library folder
//! survive a change of disk, machine and OS, which is the whole point of
//! [ADR 0010](../../../docs/adr/0010-relative-paths.md). The current location
//! is advisory, lives in `roots.json` beside `catalog.db`, and is verified
//! against a `.leyline-root` marker before anything trusts it.
//!
//! **Root 1 is the library itself**, always present and carrying the
//! library's own UUID, so a library that never adds a second root is exactly
//! the library ADR 0010 described.

use leyline_core::{LeylineError, Result};

use crate::{Catalog, db_err};

/// A folder a library may reference photos inside.
///
/// Deliberately without a path: the catalog stores identity, and asking this
/// type "where are you" is the question ADR 0085 exists to stop anyone asking
/// of a catalog row.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Root {
    /// Row id. **Root 1 is always the library itself.**
    pub id: i64,
    /// The folder's identity, matched against its `.leyline-root` marker.
    pub uuid: String,
    /// What the user calls it — "Archive 2019". Display only; nothing
    /// resolves a root by name.
    pub name: String,
    /// When the row was written, epoch milliseconds.
    pub created_at: i64,
}

/// The row id of the library's own root, which every library has (§3).
pub const LIBRARY_ROOT: i64 = 1;

impl Catalog {
    /// Every root, library first.
    pub fn roots(&self) -> Result<Vec<Root>> {
        let mut statement = self
            .conn
            .prepare("SELECT id, uuid, name, created_at FROM roots ORDER BY id")
            .map_err(db_err)?;
        let rows = statement
            .query_map([], |row| {
                Ok(Root {
                    id: row.get(0)?,
                    uuid: row.get(1)?,
                    name: row.get(2)?,
                    created_at: row.get(3)?,
                })
            })
            .map_err(db_err)?;
        rows.collect::<rusqlite::Result<Vec<_>>>().map_err(db_err)
    }

    /// The root with this identity, if the catalog knows it.
    pub fn root_by_uuid(&self, uuid: &str) -> Result<Option<Root>> {
        let mut statement = self
            .conn
            .prepare("SELECT id, uuid, name, created_at FROM roots WHERE uuid = ?1")
            .map_err(db_err)?;
        let mut rows = statement
            .query_map([uuid], |row| {
                Ok(Root {
                    id: row.get(0)?,
                    uuid: row.get(1)?,
                    name: row.get(2)?,
                    created_at: row.get(3)?,
                })
            })
            .map_err(db_err)?;
        rows.next().transpose().map_err(db_err)
    }

    /// How many folders sit in a root.
    ///
    /// The question `root-forget` has to ask before it can answer
    /// (ADR 0085 §8): a root still holding folders is a root still holding
    /// photographs.
    pub fn root_folder_count(&self, root: i64) -> Result<u32> {
        self.conn
            .query_row(
                "SELECT COUNT(*) FROM folders WHERE root_id = ?1",
                [root],
                |row| row.get(0),
            )
            .map_err(db_err)
    }

    /// Records a new root. The caller has already written its marker.
    ///
    /// The uuid is generated by the caller rather than here, because the
    /// marker on disk and the row in the catalog have to carry the same one
    /// and the marker is written first: a folder that claims an identity no
    /// catalog knows is inert, while a catalog row pointing at a folder that
    /// never got its marker is a root that can never be resolved.
    pub fn insert_root(&mut self, uuid: &str, name: &str) -> Result<Root> {
        self.ensure_writable()?;
        let now = crate::now_ms();
        self.conn
            .execute(
                "INSERT INTO roots (uuid, name, created_at) VALUES (?1, ?2, ?3)",
                rusqlite::params![uuid, name, now],
            )
            .map_err(db_err)?;
        Ok(Root {
            id: self.conn.last_insert_rowid(),
            uuid: uuid.to_owned(),
            name: name.to_owned(),
            created_at: now,
        })
    }

    /// Forgets a root.
    ///
    /// Refuses the library's own root, and refuses one that still holds
    /// folders (ADR 0085 §8) — forgetting a root whose photographs are still
    /// catalogued would leave rows nothing can ever resolve. The `RESTRICT`
    /// on `folders.root_id` would refuse it too; asking first is what turns a
    /// constraint violation into a sentence the user can act on.
    pub fn delete_root(&mut self, root: i64) -> Result<()> {
        self.ensure_writable()?;
        if root == LIBRARY_ROOT {
            return Err(LeylineError::Io(std::io::Error::new(
                std::io::ErrorKind::InvalidInput,
                "the library's own root cannot be forgotten",
            )));
        }
        let folders = self.root_folder_count(root)?;
        if folders > 0 {
            return Err(LeylineError::Io(std::io::Error::new(
                std::io::ErrorKind::InvalidInput,
                format!(
                    "this root still holds {folders} folder(s): remove those photographs \
                     from the catalog first"
                ),
            )));
        }
        self.conn
            .execute("DELETE FROM roots WHERE id = ?1", [root])
            .map_err(db_err)?;
        Ok(())
    }
}
